MiczFlor/RPi-Jukebox-RFID

htdocs/index.php

Most of the time the buttons on the web interface did not have any effect in my installation (RPi 3, raspbian stretch, vlc 2.2.6-1~deb9u1+rpi1, lighttpd 1.4.45-1). This change solves the problem.
When pushing a button in the Web UI the index.php script kills first an eventually running cvlc process. Then it launches a new cvlc process. The killing is done asynchronously in the background. The assumption is that pkill may not only stop the previously running cvlc process but also the just launched one. Therefore no sound is played. This is solved by waiting for pkill to complete before launching the new cvlc process.

Kill running player synchronousy

---

scripts/playout_controls.sh.sample

Successfully tested on my system.
Change describption: see #40

#40-enable mute toggle. vol-up/dn also unmutes if needed

---

scripts/playout_controls.sh

Adding -m 1 to the grep line for getting proper values for the volume for stereo faders. The -m 1 is not really needed in the "mute" section as it works somehow without it, but added for cleanliness.

Fix volume control for stereo fader

---

scripts/playout_controls.sh

If one is using an audio amplifier (like the pHAT BEAT) without a physical volume limiter (like a potentiometer) your Phoniebox can get very loud "accidentally". 
The maximal volume can be set in settings/Max_Volume_Limit.

Added maximum volume limit

---

misc/idle-watchdog.service

I stumbled across that issue while i was trying to start the service via web app. The service type "oneshot" lets the watchdog stay in a systemctl "starting" state, while "simple" gives a "started" state.
While it's no difference for the function of the idle-watchdog, "starting" lets a PHP script failing which should restart the service.

Fix idle-watchdog service type

---

htdocs/inc.idleShutdownSelect.php

Added the calculation to make the progress bar 60 minutes long.

Fixed idle shutdown progress bar

---

docs/INSTALL-stretch.md

This helps avoid creation of extra files when connecting from MacOS client via SMB.
The extra files make scanning directories slower and are just noise when browsing the directories using anything else than the Mac finder.

Add veto files line to smb.conf snippet

---

htdocs/inc.sleeptimerSelect.php

I changed the name for the "at" queue for the sleep timer carelessly and forgot to change that in the web app as well.

Fix for sleep timer status bar

---

scripts/rfid_trigger_play.sh

The regex required a space after the second " of url=
This works in this case:
~~~
enclosure url="https://some.mp3" length="61828556" type="audio/mpeg" /
~~~
But not in this case:
~~~
enclosure length="4960768" type="audio/mpeg" url="https://some.mp3"/
~~~

Fix for #85

---

htdocs/inc.header.php

This gives enough time to drop the url parameters.
Closes #97

Execute shutdown and reboot in background

---

scripts/playout_controls.sh
scripts/resume_play.sh
scripts/rfid_trigger_play.sh

I've simplified the "second swipe" implementation. It has only approx 10 lines now.
I've used https://github.com/MiczFlor/RPi-Jukebox-RFID/commit/d690d423cba561e6a7189a5f22edd386f5e7c24c as the base as the rfid_trigger_play.sh got confusing over the last commits.
Another change, which is not essential for the functionality of this "second swipe" implementation, is that the unused playlists in /tmp aren't deleted anymore (which was a quick hack when i wrote it). The last played folder is tracked in the Last_Folder_Played file now and read by resume play. This change is done to enable playlists in the future e.g. like in #126 .

Simple second swipe

---

htdocs/func.php

The sub folder structure requires in some places to check for relative path, not only for folder name

folder link to cards in web ui use path_rel not basepath

---

scripts/Reader_RDM6300.py

The readCard() method will only return an UUID if it's got the correct length and wasn't returned last time to prevent stuttering caused by spamming unnecessary or wrong data. Add improved error handling for SerialExceptions and close the used ports using the Serial.closed() method registered with atexit. Remove unused RPi.GPIO module from code.

Prevent spamming UUIDs, remove RPI.GPIO module, add improved error handling and a cleanup method using atexit

---

docs/MANUAL.md
htdocs/inc.header.php
htdocs/inc.loadedPlaylist.php
htdocs/inc.setSecondSwipe.php
htdocs/inc.viewFolderTree.php
htdocs/inc.viewFolderWell.php
htdocs/index.php
htdocs/lang/lang-en.php
htdocs/settings.php
scripts/installscripts/stretch-install-default.sh
scripts/playlist_recursive_by_folder.php
scripts/playout_controls.sh
scripts/rfid_trigger_play.sh

* There was a silly bug in the playlist creation: the last track was not played because it did not finish with a line break. Which means: single files did not play at all. Fixed now.
* Also, there was this discussion about the 'second swipe': https://github.com/MiczFlor/RPi-Jukebox-RFID/issues/201 I added this feature now and it can be set in the settings of the web app. The two options: either start from the beginning or toggle play / pause

Settings for 'second swipe' and bug fixes

---

docs/UPGRADE.md
htdocs/inc.navigation.php
htdocs/manageFilesFolders.php

@MiczFlor 
I think i fixed the f***ing playlist issues. It was a simple CHMOD setting, which was wrong and the result was that uploaded files had CHMOD 600 and were not readable by Mopidy. I had no problems, because i uploaded all my files with FTP. So now, all files uploaded via WebUI should run after my fix is installed.
Depending of the location of audiofolder (this is for default location):
`sudo chmod -R 777 /home/pi/RPi-Jukebox-RFID/shared/audiofolders/`
After these steps, renew your database under Folders & Files.

Urgent update! Fix for local playlist issue! Merge to develop and master!!!

---

scripts/playout_controls.sh

Some hardware mods (like [pimoroni's OnOff SHIM](https://shop.pimoroni.de/products/onoff-shim#description) - got it for 4 Euro some days ago) needs the [clean-shutdown](https://github.com/pimoroni/clean-shutdown) script to work. It's triggerd by the command 'poweroff'
Phonies playout-control script uses 'halt' to poweroff the box. AFAICS switching to 'poweroff' is possible without loosing some functionallity. 'halt --poweroff' and 'poweroff' triggers the same system cmd.
Note: The OnOff SHIM completely cut off the power from the RPi so that you can power-off and power-on from a button. Neat solution to power the box with a powerbank.

switch cmd to let clean-shutdown.sh detect halt

---

scripts/Reader.py

Hi,
I hope I got forking, branching and generating pull requests right now.
I would like to introduce my fix for the issue#231.
The KKMOON RFID Reader appears twice in the devices list as HID 413d:2107. One device is a mouse device and the other one is the keyboard device (we are interested in that).
Unfortunately the current reader code will pick the mouse device which cannot work.
My fix will additionally check if the device is a keyboard.
Any thoughts on my solution? 
Best regards
Christoph
p.s.: I just could test the code against the KKMOON reader. Can anyone check the code with other usb readers as well?

Added check if the device is a keyboard

---

scripts/installscripts/stretch-install-spotify.sh

pylast in version 3.0.0 removed support for python 2.x. So Mopidy-Iris will require pylast > 1.6 so it is tried to install the latest one, which can not run in python 2.x.
I didn't put this in the requirements.txt, because it is only needed for spotify version.

Fixed Mopidy-Iris installation (Issue #434)

---

htdocs/inc.header.php

This project is fantastic and I really want to push the code to a cleaner and more secure level.
It was really hard for me to get a quick overview of all possible commands.
The code was very verbose and full of duplicated patterns, that has grown naturally over time. My initial goal was to remove unnecessary sudo calls at least to `playout_controls.sh`. 
I decided to do this small refactoring:
- it checks GET and POST parameters and puts it into `$urlparams` variable
- all redirects happens in one place
- simple commands are defined in one array and handled directly in the logic under it
Next steps: 
Simplify remaining if constructs. Move all system calls to an own file.

(maint) inc.header.php: removes duplicate code -> better parameter overview

---

scripts/rotary-encoder.py
scripts/rotary_encoder_base.py

Hi @MiczFlor, @Yordan1976 and @dvalob noted that I confused A and B pins of the rotary encoder in the code.
I fixed that now in code and documentation in a way that the pin out stays the same and no current installations are broken. Verified on my hardware.

fix A B pin mix up

---

scripts/playout_controls.sh
scripts/rfid_trigger_play.sh
settings/rfid_trigger_play.conf.sample

Sometimes I would like to restart a playlist from the beginning. This is especially interesting for folders that have "Resume" activated. These patches implement this functionality: one can assign a card to "CMDREWIND" and that card will play the current playlist from the beginning.

Add "rewind playlist" functionality.

---

scripts/installscripts/stretch-install-default.sh

removed the german t in the sentence "your iFace ist ..."

correct small spelling error in stretch-install-default.sh

---

scripts/playout_controls.sh

As the web app is in an other directory, inc.writeGlobalConfig.sh (and all other scripts called from playout_controls.sh) has to be called with the full path.

Enable control of the global settings via web app

---

htdocs/cardEdit.php
htdocs/cardRegisterNew.php
htdocs/inc.header.php
htdocs/rss-mp3.php
htdocs/test.php

I host my phoniebox web server via https and found that site reloads are based on hard-coded "http://...." URLs.

Make URLs protocol independent

---

htdocs/inc.setWifi.php
htdocs/lang/lang-de-DE.php
htdocs/lang/lang-en-UK.php

Added the possibility to add and manage multiple WiFis with different
priorities. This feature should be handy if the box is used at different
locations.
The priority allows to prioritize a temporary mobile hotspot over
stationary WiFis for configuration.
Configurations can be deleted by deleting the SSID value.

Manage multiple WiFis with different priorities

---

misc/sampleconfigs/phoniebox-mqtt-client.service.stretch-default.sample
scripts/daemon_mqtt_client.py

First implementation of https://github.com/MiczFlor/RPi-Jukebox-RFID/issues/581
- depends on paho-mqtt lib (`pip3 install paho-mqtt`)
- can connect via user/password or certificate-based authentication
- to be done
- create service file
- include in install script

Remote control with MQTT

---

scripts/installscripts/buster-install-default.sh

use raspberry-kernel-headers for better compatibility with kernel binaries.

use raspberrypi-kernel-headers comaptible with raspberry-kernel (binaries)

---

scripts/installscripts/buster-install-default.sh

Spotify uses mopidy, local files are played with mpd. Both need to be configured during the install process

install script: MPD even if Spotify is used #583

---

scripts/inc.settingsFolderSpecific.sh

The code in `inc.settingsFolderSpecific.sh` should read the value for 
`FOLDER` only from `Latest_Folder_Played` if it is not set by its parent 
script.
Otherwise this might return with no value at all for example on the 
first media played and with wrong settings if changing playlists.
fixes #514

fix: handling of FOLDER in playlistaddplay

---

.gitignore
composer.json
composer.lock
htdocs/api/common.php
htdocs/api/cover.php
htdocs/api/latest.php
htdocs/api/player.php
htdocs/api/playlist.php
htdocs/api/playlist/resume.php
htdocs/api/playlist/shuffle.php
htdocs/api/playlist/single.php
htdocs/api/playlist/song.php
htdocs/api/volume.php
htdocs/func.php
htdocs/inc.loadedPlaylist.php
htdocs/js/jukebox.js
scripts/playlist_recursive_by_folder.php
tests/api/playListTest.php
tests/api/playerTest.php

- Rework "currentsong" response processing, split key-value pairs at ": "
- Change all response keys to lower case for further processing
- Change "playlist" command to "playlistinfo" to receive additional track info (pos, time, albumLength)
- Add singlequotes to directory shell arguments to support spaces in folders
- Remove comma from playlist name if exists, to fix collapsable tracklist
- Remove duplicate ":" from list argument
- Hide overalltime for e.g. podcasts
Introduce php-unit as testing framework
- Add composer as dependency manager
- Add phpunit and php-mock as dependencies
- Introduce namespace 'Jukebox' to enable mocking of build-in php functions e.g. "exec", "headers"

Restore missing playlist in webapp  #623

---

misc/sampleconfigs/phoniebox-startup-sound.service.stretch-default.sample

make sure startup sound also works on heedless installations. Fixes #681

changed "After" to alsa-state instead of default.target

---

scripts/installscripts/buster-install-default.sh

- Use python3.7 as the default python
- Remove mopidy-iris (only temporarily until it supports python3. See for progress https://github.com/jaedb/Iris/issues/356)
- Remove custom mopidy-spotify
- Install mopidy-spotify, mopidy-mpd and mopidy-local from the mopidy repo
- Raspbian Buster
- Neuftech USB Reader
- HifiBerry MiniAmp
- Play/Pause, Next, Prev, VolUp, VolDown GPIO Buttons
Maybe there are other setups which will break when using python3 as the default.

Fix spotify mopidy3 for buster

---

scripts/installscripts/buster-install-default.sh

doing this avoids those nasty messages complaining about locales not 
being correctly set:
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
LANGUAGE = (unset),
LC_ALL = (unset),
LC_TIME = "de_DE.UTF-8",
LC_MONETARY = "de_DE.UTF-8",
LC_ADDRESS = "de_DE.UTF-8",
LC_TELEPHONE = "de_DE.UTF-8",
LC_NAME = "de_DE.UTF-8",
LC_MEASUREMENT = "de_DE.UTF-8",
LC_IDENTIFICATION = "de_DE.UTF-8",
LC_NUMERIC = "de_DE.UTF-8",
LC_PAPER = "de_DE.UTF-8",
LANG = "en_GB.UTF-8"
are supported and installed on your system.
perl: warning: Falling back to a fallback locale ("en_GB.UTF-8").
locale: Cannot set LC_ALL to default locale: No such file or directory

fix: generate locales before installation of software

---

misc/sampleconfigs/phoniebox-activate-amplifier.service.stretch-default.sample
scripts/activate_amplifier.py

Renamed to activate_amplifier.py as the name was one of the complaints.
This script is still not perfect in the eyes of pylint, though - it 
misses docstrings badly and wasn't able to import RPi.GPIO on my 
machine.

fix: pylint activate-amplifier.py

---

ci/Dockerfile
ci/README.md

Having to re-flash the sd card of their raspberry pi did annoy me that much I created
this little set of tools to allow testing without flashing.
This is a work in progress so expect things to fail or being flaky - but it might be helpful to one or the other none the less.

Dockerfile for easier testing with docker

---

scripts/installscripts/buster-install-default.sh
scripts/installscripts/tests/ShellCheck/PhonieboxInstall.conf

I ran shellcheck and fixed all of the complaints it had about this 
script. Though at the moment I do not have a RPi to test the script is 
working correctly after my changes (I don't doubt it does run fine, but 
better be safe than sorry).
Example for shellcheck:
docker run --rm -ti -v $PWD:/code -w /code pipelinecomponents/shellcheck:latest \
shellcheck -x scripts/installscripts/buster-install-default.sh

fix: fixed all complaints of shellcheck

---

scripts/rotary_encoder_base.py

corrected failure message "AttributeError: type object 'Flags_bits' has no attribute '_fields_'" with python 3.7.3

Rotary encoder not working anymore

---

scripts/installscripts/buster-install-default.sh
scripts/installscripts/stretch-install-default.sh
scripts/installscripts/stretch-install-spotify.sh
scripts/python-phoniebox/PhonieboxConfigChanger.py

With this fix, flake8 checks also work and should catch more issues (e.g. f-strings not in Python3.5 on stretch)

hotfix: installer shall use master

---

scripts/daemon_rfid_reader.py
scripts/python-phoniebox/PhonieboxConfigChanger.py

In my fork, I got a few times the error 
`  Downloading pyflakes-2.1.1-py2.py3-none-any.whl (59 kB)
Installing collected packages: mccabe, pycodestyle, entrypoints, pyflakes, flake8
Successfully installed entrypoints-0.3 flake8-3.7.9 mccabe-0.6.1 pycodestyle-2.5.0 pyflakes-2.1.1
./scripts/python-phoniebox/PhonieboxConfigChanger.py:69:27: F821 undefined name 'configFilePath'
config_file = configFilePath
^
1     F821 undefined name 'configFilePath'
1
##[error]Process completed with exit code 1.`
it seems that this part was not required  is actually not required, as the config file is not written during execution of the set command in the PhonieboxConfigChanger.
Therefore i removed that part of the code.
@laclaro : Please check if you are fine with that change

Fixing code to pass Action Python package

---

scripts/installscripts/buster-install-default.sh

Since mopidy-2.3 was removed from mopidy apt repository, install 2.2 from main buster repository.

Install mopidy-2.2.2-1 from main repository

---

scripts/installscripts/buster-install-default.sh
scripts/installscripts/stretch-install-spotify.sh

Mopidy-Iris dropped python 2 and mopidy 2 support after 3.43.0, see https://github.com/jaedb/iris/releases
Pin used version to 3.43.0

Pin mopidy-iris to last version working with python 2

---

requirements-spotify.txt
scripts/installscripts/buster-install-mopidy3.sh

Added requirements.txt files, not thoroughly tested yet.
Advantages:
- pinning of package versions which work
- Github security alerts for dependencies
See #803

Use requirements.txt

---

scripts/installscripts/buster-install-default.sh
scripts/installscripts/stretch-install-default.sh
scripts/installscripts/stretch-install-spotify.sh

This will remove FPM as it does not seem to be needed but uses precious system resources.
Please check thoroughly, but as far as I could see lighttpd only used the php-cgi in its implementation. After manually disabling the fpm package from my sons box everything (the phoniebox webinterface) still worked fine.

chore: remove php-fpm

---

scripts/installscripts/buster-install-default.sh

Should fix #842 on **master** 
Untested yet.

Hotfix: installation of py packages now for python 3

---

ci/Dockerfile.buster.amd64
ci/Dockerfile.buster.armv7
ci/Dockerfile.stretch.amd64
ci/Dockerfile.stretch.armv7

while installing RPi-Jukebox-RFID in docker I get a lot of
`debconf: falling back to frontend: Readline`
Messages.
Found a fix and implemented it:
https://github.com/phusion/baseimage-docker/issues/58#issuecomment-47995343
Linked issue: #715

Enhance docker buster image

---

scripts/installscripts/tests/test_installation.sh

This script allows to determine if the buster-install-default.sh installation script works as expected. It does not check *everything*, but most of the important parts.

Add test_installation.sh script

---

requirements.txt

in #912 issues in pi-rc522 were found, which are fixed on their master branch. However we use the package on https://pypi.org/project/pi-rc522/ which wasn't updated since 2017.
I opened this PR to start a discussion, if we want to install from Github to get the latest update. Disadvantage is that their master branch may be unstable.

use latest version of pi-rc522 from Github

---

.github/workflows/pythonpackage.yml
components/gpio_control/requirements.txt

I added the python tests used by the components to Github Actions to run on commit.
@veloxidSchweiz, could you check, if this makes sense?

Use pytest in github actions

---

scripts/installscripts/buster-install-default.sh

This should make interaction with scripts a bit simpler, since the conf
file will always be created in the HOME_DIR and not in the dir where the
install script is located.
Also:
* create the log dir in the HOME_DIR as well
* renamed the log dir to "phoniebox_logs"

Always create the PhonieboxInstall.conf file in HOME_DIR

---

htdocs/inc.processAddNewStream.php

Hi folks,
I created Issue #939 and have a fix here.
- corrected a typo which led to empty _audiofolderNew_ value
- added missing creation of shortcut entries
Not sure if this is your preferred location to add the missing creation of shortcut entries. Chose to go the same way as done in `RPi-Jukebox-RFID/htdocs/inc.processAddYT.php`.
It is not quite clear to me, whether you might prefer to handle the creation of shortcuts within more central `RPi-Jukebox-RFID/htdocs/inc.processCheckCardEditRegister.php` where this step is handled for other non-stream media.
Cheers :-)

Fix link stream not possible

---

components/audio/PirateAudioHAT/README.md
components/audio/PirateAudioHAT/setup_pirateAudioHAT.sh
components/rfid-reader/PN532/README.md
components/rfid-reader/PN532/reset_pn532.sh
components/rfid-reader/PN532/setup_pn532.sh
scripts/Reader.py
scripts/installscripts/buster-install-default.sh

* Add setup scripts to make installation and setup of the PN532 RFID reader and the Pimoroni PirateAudio HAT a lot easier.
* Fix issue in Reader.py with whitespaces/newlines when value is read from deviceName.txt file
* Do not Install Python requirements for PN532 RFID reader by default during a normal installation. Instead, install it on demand from the dedicated setup script.
PS.: Sound already works fine with the PiratedAudio HAT. The display on the HAT will require a bit more configuration and testing, before it works with Phoniebox.

Add setup scripts for PN532 RFID reader and PirateAudio HAT

---

components/rfid-reader/PN532/requirements.txt
components/rfid-reader/RC522/README.md
components/rfid-reader/RC522/requirements.txt
requirements.txt

As discussed in #948.
Not sure if anything is missing here.
* Should RPi.GPIO be moved to components/rfid-reader/RC522/requirements.txt as well?
* Is any other kind of setup necessary?
I won't be able to test this, since I don't have a RC522 compatible RFID reader.
Next step is a separate setup/installation script that can be started at the end of the main installation script to setup special components like RFID readers, displays and sound cards.

Move RC522 related setup to components folder

---

misc/sampleconfigs/gpio-buttons.py.sample

@hamsert reported in issue #896 that lower bounce time worked much better for rapid button clicks.

Reduce bounce time of buttons

---

.github/workflows/dockerimage.yml
ci/Dockerfile.buster.test_install.amd64
scripts/installscripts/buster-install-default.sh
scripts/installscripts/tests/run_installation_tests2.sh
scripts/installscripts/tests/test_installation.sh

This should make the installation more easy and avoid confusion, e.g. #1001 
I tested installation on a docker image (which worked fine), but not with real reader hardware, because I don't have any reader available.

Integrate scripts to install RC522 and PN532 reader

---

misc/sampleconfigs/mpd.conf.buster-default.sample

See #685, thanks to @belinea4071.
Currently only for MPD in classic edition, couldn't find a setting so far in mopidy.

Enable volume normalization

---

htdocs/ajax.loadMopidyStatus.php
scripts/startup-scripts.sh

The problem is, that mopidy.SERVICE (Spotify) is starting very quick. But while the SERVICE is already running, mopidy is establishing the SERVER connection to localhost:6600 in the background. This needs ~ 30-60 seconds, depending on how much playlists the user has.
Only when the server is running, you can give commands (volume, starting songs from spotify, ...)
- I added seperate informations about service and server to the info-tab.
- Adding a while-loop for checking the mopidy/MPD server status in the startup-script.
Fixes #1024

Wait until server is running

---

htdocs/inc.viewFolderTree.php

For explanation: My solution uses the webUI of open.spotify.com and so, this is a complete other but better way of getting informations like before with the Mopidy.Core.API because the webUI is creating the "title" dynamically based on the given mediatype (see examples). I didn't find a way to get the "name" if using mediatype "artist" or "album" in the LibraryController or PlaylistController.
Additionally i use this JSON-URL to get the cover.
Both informations are retrieved ONCE for each URL. If they're saved, they will not be retrieved again, unless they were deleted.
If someone please can test my pull request and if it's working, the old code could be removed in reorga.
Examples:
Artist: https://open.spotify.com/oembed/?url=spotify:artist:0H39MdGGX6dbnnQPt6NQkZ&format=json
Album: …

Fix for getting infos from Spotify (now supporting album + artist URLs)

---

components/gpio_control/install.sh

The `chown` command in line 61 changes the ownership of the gpio_settings.ini to the correct user. Because the script is run with sudo command root is the of ~/.config/phoniebox  which leads to an error in gpio_control.py. The altered `chown` command leads to the folder and the the .ini to be owned by the correct user.

Fix incorrect ownership of ~/.config/phoniebox

---

scripts/Reader.py.Multi
scripts/Reader.py.experimental.Multi
scripts/RegisterDevice.py.Multi
scripts/installscripts/buster-install-default.sh

Issue #760
To use it, the two files Reader.py and RegisterDevice.py must be replaced with the *py..Multi files.
If you activate multiple RFID readers it´s e.g. possible to read Card and "Figure" RFID parallel.

Added option for multiple RFID Readers

---

htdocs/lang/lang-de-DE.php
htdocs/lang/lang-en-UK.php
htdocs/lang/lang-nl-NL.php
htdocs/systemInfo.php

As phonieboxes might lack of a proper cooling solution, temperature should be visible in the web interface. Great to have as an indicator in case of issues or simply for monitoring temperature in hot environments (kids room under the roof etc).

Add RPi's temperature info to web interface

---

htdocs/func.php
htdocs/inc.viewFolderTree.php

Fix for the WebUI, @MiczFlor reported here https://github.com/MiczFlor/RPi-Jukebox-RFID/pull/1028#issuecomment-668083796.
There was a missing </div> which results in displaced folders.

Fix for WebUI

---

components/gpio_control/gpio_control.py

When using the gpis_settings.ini in its current form I was getting these error when running gpio_control.py. 
```
File "/usr/lib/python3.7/configparser.py", line 802, in _get
return conv(self.get(section, option, **kwargs))
ValueError: could not convert string to float: '0.1 ; only for rotary encoder'
```
I read a little about the topic and it seems that configparser does not support inline comments in its default state. Therefore the config argument was added.
Works on my machine, but not extensively tested beyond that.

Add option to ConfigParser to support inline-comments

---

components/gpio_control/function_calls.py

This addition allows seeking forward and backward via GPIO buttons.
A sample configuration would look like:
`[Forward]`
`enabled: True`
`Type: Button`
`Pin: 19`
`pull_up: True`
`functionCall: functionCallPlayerSeekFwd`
`[Back]`
`enabled: True`
`Type: Button`
`Pin: 20`
`pull_up: True`
`functionCall: functionCallPlayerSeekBack`
Unfortunately, there seems to be an open issue in Music Player Daemon preventing the "seek back" functionality.
See also issue #1031

Allow seeking via GPIO buttons

---

scripts/startup-scripts.sh

Modified startup-scripts.sh to execute mpg123 with the configured startup volume from global.conf.
The configured volume from global.conf was ignored when playing the startup sound (always played at 100%, which can be extremely loud for kids).
Now the configured volume is converted into the correct volume value for mpg123 (100% volume converts into 32768).

Play startup sound with correct startup volume

---

scripts/inc.writeGlobalConfig.sh
scripts/playout_controls.sh

Adds an option to configure the poweroff command executed when
triggering a shutdown. Poweroff command to use is read from file
`settings/Poweroff_Command`, default `sudo poweroff`.
Scenario:
- You are powering you Pi via an extension board, e.g. MoPi 2,
that cannot detect a regular poweroff and stays powered-on itself. Via a
customizable poweroff command you can trigger the extension board to
power off the Pi in the prefered way which finally also turns-off the
extension board.
- You like to add some extras, e.g. LED illumination, on power off. A
customizable poweroff command provides the "user" a nice hook for whatever
stuff he likes to add before the actual power off :-)

Added customizable poweroff command

---

scripts/inc.writeGlobalConfig.sh

Fixes #1167.
Default value was 0, so users would assume startup sound doesn't work.

Fix volume of startup sound

---

scripts/playout_controls.sh

As there is a savepos-command in "playerstop" this should also be included in "playerstopafter".

missing savepos-command in "playerstopafter"

---

requirements-spotify.txt

As many fixes were done since 3.45.0 we pin Mopidy Iris to the latest version.
I don’t have Spotify, so I can’t test this.

Update Mopidy Iris to 3.54.2

---

components/gpio_control/function_calls.py

fix: let function_calls.py work with python 3.5

---

scripts/playout_controls.sh

This shortcuts in `playout_control.sh` reduces the execution time of `volumeup`, `volumedown` etc. on my RPi Zero by the half:
```sh
pi@raspberrypi:~/RPi-Jukebox-RFID/scripts $ time ./playout_controls.sh -c=volumedown
Simple mixer control 'Master',0
Capabilities: volume
Playback channels: Front Left - Front Right
Capture channels: Front Left - Front Right
Limits: 0 - 255
Front Left: 3 [1%]
Front Right: 3 [1%]
real    0m0.615s
user    0m0.232s
sys     0m0.290s
#after
pi@raspberrypi:~/RPi-Jukebox-RFID/scripts $ time ./playout_controls.sh -c=volumedown
Simple mixer control 'Master',0
Capabilities: volume
Playback channels: Front Left - Front Right
Capture channels: Front Left - Front Right
Limits: 0 - 255
Front Left: 3 [1%]
Front Right: 3 [1%]
real    0m0.290s
user    0m0.159s
sys …
```

Shortcuts volume commands of playout control

---

scripts/installscripts/buster-install-default.sh
scripts/installscripts/tests/test_installation.sh

On Buster Lite images ALSA is not preinstalled. But the install script should install all dependencies.
Thanks to @mattelacchiato
https://github.com/MiczFlor/RPi-Jukebox-RFID/discussions/1208#discussioncomment-255616

Ensure ALSA is installed

---

htdocs/api/common.php
htdocs/api/player.php
scripts/inc.writeGlobalConfig.sh
scripts/playout_controls.sh

Running Phoniebox(+Spotify) on a Raspberry Pi Zero. Using the webui I noticed the player.php call takes up to 5 seconds to process on the zero which leads to a non ideal user experience.
With 3 tweaks I managed to improve the performance of a player.php call by a factor of 10 for the most common scenarios.
Avoid all system calls:
1. Use direct socket communication to mpd instead of netcat
2. Avoid separate volume fetching when not necessary by checking global config first
3. Avoid Chapter fetching by checking file type. This section is not perfect yet. I would propose to put the chapter extensions in a central config but need feedback what would be the best solution to do this.

Improve player.php performance

---

htdocs/inc.processCheckCardEditRegister.php
htdocs/lang/lang-de-DE.php
htdocs/lang/lang-en-UK.php
htdocs/lang/lang-nl-NL.php

Reason for improvement:
Running Phoniebox(+Spotify). I was adding multiple albums/playlists from spotify to Phoniebox when realizing I couldn't just copy&paste the urls. 
Result:
All Urls from https://open.spotify.com get converted to the mopidy format and are redisplayed in the correct format.
Proposal:
Use a regex replacement inside inc.processCheckCardEditRegister.php to validate/replace the url.

Spotify url conversion (http to mopidy format)

---

scripts/installscripts/buster-install-default-with-autohotspot.sh
scripts/installscripts/buster-install-default.sh
scripts/installscripts/stretch-install-default.sh

Provide possibility to keep USB button encoder mappings during update.
tested with buster-install-default.sh

feat: keep USB Button Encoder settings during update

---

components/controls/buttons_usb_encoder/README.md
components/controls/buttons_usb_encoder/buttons_usb_encoder.py
components/controls/buttons_usb_encoder/map_buttons_usb_encoder.py
components/controls/buttons_usb_encoder/setup-buttons-usb-encoder.sh

There is a possibility, that the buttons USB encoder sends a list of pressed keys. The previous implementation ended up in an error. This fix now handles lists of keycodes.
Additionally there is a hint that the setup script has to be executed from RPi home directory.

fix: handle list of keycodes in buttons usb encoder

---

components/gpio_control/example_configs/gpio_settings.ini

Added two new entries for Fast Forward and Rewind in the gpio_settings.ini  (disabled by default)

FF and Rewind added to GPIO_SETTINGS.ini

---

docs/INSTALL-COMPLETE-GUIDE.md

Ever since I built my first Phoniebox, I wanted to contribute to the project. It never worked out until now. I just set up a second device and I struggled a bit. You guys have a lot of great documentation but 1) some of it is outdated, 2) most of it is all over the place (Markdown, Wiki, Discussions, Gitter) and 3) to some extend it is not complete.
For example, I wanted to set up the Phoniebox with Spotify support. During the install script (great addition btw, last time for me was all manual), I was asked to provide client_id and client_secret. But there is no documentation about where to get this data nor does it tell you whether your inputs have worked or not.
I took the opportunity to document my installation journey. It's opinionated of course, I have chosen a specific hardware set …

Add documentation Complete Install Guide

---

scripts/daemon_rfid_reader.py

See #1097 
implementation proposed by @Toqqi in https://github.com/MiczFlor/RPi-Jukebox-RFID/commit/786ecf4874db54c0fd6257a7aa8cf8fe611c0232:
Description from @Toqqi:
I used the signal python library to detect when a RC522 RFID reader stops reading in a card ID for one second.
This then triggers the playerpauseforce action in playout_controls.sh.
I then configured the second swipe action to be "resume playback" to achieve the play/pause effect when moving an RFID card to/from the reader.
@Toqqi, could you check, if that's what you propsed?

implementing stop on removal for RC522 

---

scripts/Reader.py.experimental

I had recently some issue with the RDM6300 reader, during debugging I found I would be very nice to have matching Numbers between the entries in the Database and the ones printed on the ID-Cards itself.  
On the ID-Cards I am having are two Numbers, one 10 Digit Number with leading zeros and a fractional number. 
Both are based on the same card number, just with a different representation. The Format is called Wiegand26. 
Also  I added a XOR checksum check  as it is described in the RDM6300 Manual.
Additionally I tried to Address the dependency Topic of #1105, but this is mostly untested, since I don't have this modules available. It would be very nice if someone could support here.

RDM6300 addtional output formats, XOR Checksum 

---

htdocs/func.php
htdocs/inc.viewFolderTree.php
htdocs/index.php

Resolving #469 by simplifying collapse IDs in folder tree.
Make use of integers for collapse IDs rather than folder names to avoid
problem with any kind of non-allowed characters as ID value.
Simplifies corresponding code as no character replacement is required
for collapse IDs anymore.

(bugfix) Fixes bug in folder tree, related to special chars

---

.github/workflows/pythonpackage.yml
components/gpio_control/test/test_gpio_control.py

Fix unit test and remove Python 3.5 check

---

scripts/daemon_rfid_reader.py

The merge of #1122 missed @Toqqi comment https://github.com/MiczFlor/RPi-Jukebox-RFID/pull/1122#issuecomment-740609470 which provided an update (https://github.com/Toqqi/RPi-Jukebox-RFID/commit/4e1a6fc22a5afc6d31d97b406546fe26cefa184b) that incorporates the global switch, merged with #1130.
Now, "stop on removal" is an option and no must.

(bugfix) stop on removal, incorporate switch

---

components/gpio_control/GPIODevices/led.py
components/gpio_control/example_configs/gpio_settings_status_led.ini
components/gpio_control/gpio_control.py
components/gpio_control/test/gpio_settings_test.ini

Adds a status LED GPIO control that lights up the LED if the phoniebox
is ready (finished startup scripts, checked via systemctl). Type called
`StartupScriptsStatusLED`.
Comparison to MPDStatusLED:
MPDStatusLED lights up the LED if MPD is started which is (on a RPi
zero seconds) before the phoniebox is actually ready for its first card.
Therefore, another status LED indicating whether startup completely
finished appears useful.

Added ready-for-card status LED GPIO control

---

scripts/inc.writeGlobalConfig.sh
scripts/playout_controls.sh
scripts/rfid_trigger_play.sh
settings/rfid_trigger_play.conf.sample

Adds a feature to switch between two audio iFaces (e.g.
speaker/headphone). Audio iFaces to swap are stored in files
`settings/Audio_iFace_Name_[01]` and need to be set manually, if feature
should be activated. The correlating volumes are stored in files
`Audio_Volume_Level_[01]`. Currently active iFace "ID" (0 or 1) is
stored in file `settings/Audio_iFace_Active` (default 0).
Scenario: You have equipped your Pi with a sound card that provides a
separate output (and volume control) for speaker and headphone, like the
WM8960 Hi-Fi HAT. This feature enables you to switch between the two
outputs. It can be triggered by RFID card or (not implemented) via GPIO
(button or switched jack). Compare discussion in #636, #786.
Restriction: Only works with `amixer` as volume manager and MPD output …

Added switchable audio iFaces

---

scripts/Reader.py.pcsc

Rewrite of the pc/sc-support mentioned in #533  with help of pyscard instead of rfidiot which doesn't seem to work with python3 anymore. 
Requirements: installed pcscd and python-pyscard packages. First found reader is used for reading tags.

added support for pc/sc readers

---

.github/CODEOWNERS
components/controls/buttons_usb_encoder/buttons_usb_encoder.py
components/controls/buttons_usb_encoder/map_buttons_usb_encoder.py

Script can only be executed if sys.path.append(".") is executed before imports.
This bug (https://github.com/MiczFlor/RPi-Jukebox-RFID/pull/1249#issuecomment-803221057) I think was accidentally introduced with change #1332.
Also introduced git CODEOWNERS file, which automatically adds reviewers if a PR affects a specific scope. For now I just configured myself. File can be updated for everyone needs :-)
https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/about-code-owners

fix: move path append command in buttons usb encoder

---

.gitignore

`settings/PhonieboxInstall.conf` holds secrets like wifi passwords and others, which should not get checked into VCS.

Ignore settings/PhonieboxInstall.conf

---

scripts/playout_controls.sh
scripts/rfid_trigger_play.sh
settings/rfid_trigger_play.conf.sample

These additional commands ease the creation of special "surprise" RFID cards, buttons etc.
Following commands have been added to playout_controls.sh:
**randomcard** and **randomfolder**: Both allow to start playing an arbitrary folder/playlist. Since some phonieboxes might have either abandoned card IDs (cards formerly registered but the folder is gone) or abandoned folders (files copied but no card is assigned) the user can decide which command / selection strategy he prefers.
**randomtrack:** Jumps to a random track within the current playlist. This happens without touching the shuffle settings, i.e. the playlist order remains untouched. Playback will normally continue with the following tracks. This command is especially useful if your playlists contain complete (1-track) episodes and …

Additional commands to play random cards/folders or tracks

---

scripts/cli-player.py
scripts/organizeFiles.py

organizeFiles: I added a small script for conveniently organizing audio folders, linking them to RFID cards, finding audio folders that are currently not bound to any RFID card, and fixing broken links.
I wrote this script as a replacement for the phoniebox-web-ui, since I'm running out of memory when using the web-ui on a raspberry pi zero. Using this small script significantly reduces resource usage on the system, so that works pretty well in my case.
Hope this might help someone.

command line script for linking RFID cards to folders & fixing broken links 

---

src/jukebox/player/PlayerMPD.py

the PlayerMPD now polls the mpd status each 250ms internally. 
The improvement here is that the internal mpd_status does not depend any more on the web ui
E.g. the JukeBox can now be exited any time without the need of extra mpd status polling, the status just 250ms old, which is probably acceptable for song continuation after restart.
This can also be the point to think about pub/sub for this information
The initial approach of using asyncio for that purpose has been discarded since asyncio depends on a main loop, 
which is not existing here. 
Instead the polling is done by a thread and thread safty has been added to the mpd calls via a mutex
TODO:
- as @ChisSoc mentioned before we need to think about a defined method to exit all the threads in all the modules , this is also not solved …

addedd internal mpd status polling

---

src/jukebox/player/PlayerMPD.py

The Issue was that the some mpd command where used without mutex.
instead of 
`self.mpd_client.currentsong`
to use
`self.mpd_status.update(self.mpd_retry_with_mutex(self.mpd_client.currentsong))`
Anyway, the current song is already part of the status.

fixed mpd already connected error

---

scripts/installscripts/buster-install-default.sh
scripts/installscripts/tests/test_installation.sh

#1255 misses the `alsa-utils` package that is needed make it work on buster-lite

fix-alsa on buster-lite

---

htdocs/inc.header.php
htdocs/inc.setBootVolume.php
htdocs/inc.setStartupVolume.php
htdocs/lang/lang-de-DE.php
htdocs/lang/lang-en-UK.php
htdocs/settings.php
scripts/inc.writeGlobalConfig.sh
scripts/playout_controls.sh
scripts/startup-scripts.sh

Referencing @BerniPi comment in https://github.com/MiczFlor/RPi-Jukebox-RFID/pull/1169 , this adds a new value to the global.conf -> the global level of the audio mixer after any boot of the Raspberry Pi.
The value can be set in the Web UI
NEEDS TESTING!!!
@BerniPi - I invited you as a collaborator, please accept the invitation (don't know if and where it will reach you. Mail?)

Adding a boot volume settings to be set in startup script after reboot

---

scripts/installscripts/buster-install-default.sh

in order to easily support the debian upgrade path (replace `buster` with `bullseye` in `/etc/apt/sources.list` and `/etc/apt/sources.list.d/*`)
this change helps transition from `php7.3` on buster to `php7.4` on bullseye
and use python3 for python which is valid on bullseye

facilitate transition to bullseye

---

src/webapp/src/components/Settings/dialogs/reboot.js
src/webapp/src/components/Settings/dialogs/shutdown.js
src/webapp/src/components/Settings/systemcontrols.js
src/webapp/src/context/player/index.js

This commit connects both backend plugins `Reboot` and `Shutdown` to the Webapp. A user can now execute both commands directly from the UI.

[Webapp] Introduce Reboot and Shut Down

---

installation/routines/setup_jukebox_core.sh

During install, I received this error when installing `pyzmq`
```
Collecting pyzmq
Downloading https://files.pythonhosted.org/packages/6c/95/d37e7db364d7f569e71068882b1848800f221c58026670e93a4c6d50efe7/pyzmq-22.3.0.tar.gz (1.2MB)
Installing build dependencies: started
Installing build dependencies: finished with status 'error'
Complete output from command /usr/bin/python3 -m pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-5da89x76 --no-warn-script-location --no-binary :all: --only-binary :none: -i https://pypi.org/simple --extra-index-url https://www.piwheels.org/simple --pre -- setuptools wheel packaging "cffi; implementation_name == 'pypy'":
Ignoring cffi: markers 'implementation_name == "pypy"' don't match your environment
Looking in indexes: …
```

[Bugfix] pip install fails sometimes when not updated initally

---

src/jukebox/components/battery_monitor/BatteryMonitorBase.py
src/webapp/src/components/Settings/helpers/battery-icon.js
src/webapp/src/components/Settings/index.js
src/webapp/src/components/Settings/status.js
src/webapp/src/components/Settings/systemcontrols.js
src/webapp/src/config.js

* New section in Settings called "System Status"
* Currently includes
* Jukebox version
* Battery Charging status when plugin is loaded

Add Monitoring with Battery and Jukebox Version

---

src/jukebox/components/rfid/hardware/rc522_spi/requirements.txt

Fixes:
~~~
Collecting pi-rc522
Cloning git://github.com/ChisSoc/pi-rc522.git to /tmp/pip-install-9ufnoeqv/pi-rc522_675a00eee274444790e977f26418741c
Running command git clone --filter=blob:none -q git://github.com/ChisSoc/pi-rc522.git /tmp/pip-install-9ufnoeqv/pi-rc522_675a00eee274444790e977f26418741c
fatal: remote error:
The unauthenticated git protocol on port 9418 is no longer supported.
Please see https://github.blog/2021-09-01-improving-git-protocol-security-github/ for more information.
WARNING: Discarding git+git://github.com/ChisSoc/pi-rc522.git#egg=pi-rc522. Command errored out with exit status 128: git clone --filter=blob:none -q git://github.com/ChisSoc/pi-rc522.git /tmp/pip-install-9ufnoeqv/pi-rc522_675a00eee274444790e977f26418741c Check the logs for full command output.
ERROR: …

Update to encrypted git protocol for RC522 dependency download

---

installation/includes/05_finish.sh
installation/install-jukebox.sh
installation/routines/customize_options.sh
installation/routines/setup_git.sh
installation/routines/setup_jukebox_core.sh
installation/routines/setup_jukebox_webapp.sh
installation/routines/setup_rfid_reader.sh

In case a `cd` or similar fails, the installation aborts rather than continue installation routines in wrong directory. 
This prevents the effect of #1685. 
(In #1685 the could be an improved fix as well: removing temporary directories before. However, this PR prevents ill effects in case no custom error handling is implemented)
Also fixes a few ShellCheck warnings.

Add exit_on_error handler for install routines

---

src/jukebox/components/playern/backends/interfacing_mpd.py
src/jukebox/components/playern/core/__init__.py

This gives a working version for MPD folder / album playback:
- player.mpd:
- get_albums / get_album_tracks
- get_folder
- player.ctrl:
- get_queue (currently in MPD format!)
- next / prev /play / toggle
- play_uri, where uri can be mpd:folder:xyz or mpd:album:xyz:albumartist:uvw
Not implemented yet:
- status publishing (but status is printed on console log)
- random, repeat
- save state and folder resume
- podcasts / livestreams
Always go through player.ctrl if possible. If the same function also exists in player.mpd it is for testing / developing

Implement folder and album playback in Async MPD Interface

---

scripts/playlist_recursive_by_folder.php

- Fixes https://github.com/MiczFlor/RPi-Jukebox-RFID/issues/1774
When the podcast xml grabbed from the url contained line breaks in the enclosure tag, fetching the audio files did not work. With this fix it is possible again.

Fixed issue with reading podcasts xml with line breaks in enclosure tag

---

htdocs/inc.viewFolderTree.php

Spotify returns a bad request when no user-agent is given.
Simple way to reproduce: 
```
<?php
// demo code to reproduce:
$headers = stream_context_create(array('http'=>array('method'=>'GET', 'header'=>'user-agent:Phoniebox')));
$url = "https://open.spotify.com/oembed?url=spotify:playlist:4wFsylSpjoor3HXkle80sa&format=json";
echo "This will work:\n";
echo file_get_contents($url, false, $headers);
echo "\n\nThis will fail (400 Bad Request):\n";
echo file_get_contents($url);
?>
```
Therefore I added a simple user-agent to all spotify requests. It is similar and inspired by the solution of @acidburn78 but without adding a new dependency.

#1309, #1451 Fixes missing title and cover for spotify playlists by adding user-agent

---

components/smart-home-automation/MQTT-protocol/README.md
components/smart-home-automation/MQTT-protocol/daemon_mqtt_client.py
components/smart-home-automation/MQTT-protocol/requirements.txt

Added a new topic that the MQTT daemon will publish messages on. This is about immediate event-based messages (in contrast to periodic) with currently the only event being the "card swiped" event. It makes use of inotify to watch for changes to the `Latest_RFID` file and immediately sending the card ID to the MQTT server.
That way also cards that are not assigned to media or an action within Phoniebox will get relayed to the MQTT server allowing to e.g. control your smart home via the Phoniebox (e.g. having a "dim the lights" card to change lights while not interfering with the current playback).
It's an implementation of the idea presented in https://github.com/MiczFlor/RPi-Jukebox-RFID/pull/1492 but directly integrated into the MQTT daemon rather than the RFID daemon.

Publish "card swiped" event via MQTT

---

.github/workflows/dockerimage.yml
ci/Dockerfile.buster.test_install_altuser.amd64
scripts/installscripts/buster-install-default.sh
scripts/installscripts/tests/run_installation_tests2_altuser.sh
scripts/installscripts/tests/run_installation_tests3_altuser.sh
scripts/installscripts/tests/run_installation_tests_altuser.sh
scripts/installscripts/tests/test_installation_altuser.sh

Replacing /home/pi with the home folder of the current user (`echo $HOME`)
- Created docker test with alternative user `hans`
- Installed with user `hugo` on my RPi3 (classic installation)
- uploaded and listened to one mp3 file
- Installed with user `pi` on my RPi3 (classic installation)
- uploaded and listened to one mp3 file
- GPIO
- RFID
- Buttons

Remove hardcoded homedir in install scritp

---

misc/sampleconfigs/gpio_settings.ini.sample

**Short version:**
- This replaces the  'misc/sampleconfigs/gpio_settings.ini.sample' (untouched since 11 months) with the current 'components/gpio_control/example_configs/gpio_settings.ini', which contains the latest syntax
- A few example buttons were enabled by default. I changed these to disabled too. Reason: I think it's no good idea to configure concrete GPIO ports (without knowing the user's hardware setup!), just because a user activated the GPIO control component at installation.
**Longer version:**
Background for bullet #1 was that, after Release 2.3, a user reported an issue with a shutdown button reacting too quickly on a fresh install ( https://github.com/MiczFlor/RPi-Jukebox-RFID/issues/1509  ). This was quickly resolved after identifying a missing line in the GPIO sample …

Fix samplecfg for GPIO component

---

scripts/installscripts/buster-install-default.sh

The installation of mopidy would fail for me. Adding the key like suggested in the documentation fixed it for me: https://docs.mopidy.com/en/latest/installation/debian/

fix(install): updates the URL and adds missing key

---

scripts/Reader.py.experimental

Hi There,
First of all, thank you very much for that great project. I recently made a box as Christmas present and enjoyed very much working on it.
I had a little trouble getting the RFID-RC522 running. I used the Reader.py.experimental script for reading RFID tags.
The problem seems to be, that the line from the deviceName.txt is just taken as device name but the line seems to have several columns separated by ';'.
I improved the code by copying over a snippet from the Reader.py.experimental.Multi to split the line at ';'.
Could you please double check if this works on your side to.
Thank you and best regards,
Daniel

Reader.py: split line read from deviceName.txt

---

docs/GPIO-BUTTONS.md

Article in the wiki has been updated, this one is deprecated -> maybe remove entirely?

(docs) GPIO-Documentation in /docs is deprecated

---

scripts/installscripts/buster-install-default-with-autohotspot.sh
scripts/installscripts/buster-install-default.sh

Follow up of https://github.com/MiczFlor/RPi-Jukebox-RFID/pull/1789/files fixing the issue also for the spotify install

fix(install): mopidy for spotify install

---

src/jukebox/run_configure_audio.py

Fixed parsing in run_configure_audio.py by editing '\n' and '#' characters.

Fix newline/comment generation in run_configure_audio

---

components/smart-home-automation/MQTT-protocol/daemon_mqtt_client.py

This change adjusts the regex to read the correct duration and fixes the issue that currently duration is always 0 reported via mqtt. (Mentioned here: https://github.com/MiczFlor/RPi-Jukebox-RFID/discussions/1353#discussioncomment-2327099) 
In the status response the duration is not existing anymore and now it is getting reported as `time: 22:200`
This means the first part is the elapsed time and the second part is the actual duration of the track.
Example how the attribute gets send now via mqtt

fix reported duration attribute via mqtt

---

scripts/installscripts/buster-install-default.sh

Follow-up for commit "facilitate transition to bullseye".
Bug: Since bullseye uses php7.4, php.ini will not be replaced by the sample
Solution: Read folder name in /etc/php and use it in variable php_ini, keeping compatibility with buster

flexible php version in variable php_ini

---

components/smart-home-automation/MQTT-protocol/README.md
components/smart-home-automation/MQTT-protocol/daemon_mqtt_client.py

This PR adds the `repeat_mode` attribute to mqtt. This will have one of the three values used in [playout_controls.sh#L865](https://github.com/MiczFlor/RPi-Jukebox-RFID/blob/develop/scripts/playout_controls.sh#L865) `off`/`single`/`playlist`.
Also part of this PR is also some cleaning up of duplicated code. If you want I can separate the PRs as well.

feature: add repeat mode attribute to mqtt

---

.github/workflows/pythonpackage.yml

Updated Python versions used for CI.
3.6 is not available anymore, see https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json

Updated Python versions to use for CI

---

src/jukebox/components/gpio/gpioz/README.rst

Fix used alias in example for shutdown button. Using GPIO 3, as it allows waking a raspi from halt state [1].
[1] https://elinux.org/RPI_safe_mode#cite_note-1

Update 'GPIO Recipes'  for power button

---

resources/default-settings/gpio.example.yaml
src/jukebox/components/gpio/gpioz/README.rst

Hello,
I tried to replace a legacy phoniebox with future3 and struggled with the shutdown button, because the documentation seemed only half correct. I fixed that and added an example to the gpio config.

Fixed documentation and example for shutdown button

---

README.md
requirements-gmusic.txt

GMusic is no longer available (see https://play.google.com/music).
also mopidy-gmusic is deprecated, so removing also here.

Remove Gmusic

---

components/audio/PirateAudioHAT/README.md
components/audio/PirateAudioHAT/setup_pirateAudioHAT.sh

Fix #1974
important to note that early revisions of PirateAudio HAT used bcm20 for Volume up, later revisions use bcm24. See also https://github.com/pimoroni/pirate-audio/issues/63#issuecomment-916860634

Fix Pirate Audio Button Volume Up

---

.github/workflows/dockerimage.yml

Using existing GitHub Actions for the Docker job should utilize caching and improve duration of the job.

Use existing actions for Docker GitHub Action

---

scripts/rfid_trigger_play.sh

unquoted "is set" check fails if var is not set and if-statement has a subsequent check. Further the preceding "is empty" check is sufficient in this case.

removed "is set" check (#1967)

---

.github/workflows/pythonpackage.yml

Added python 3.10 to version matrix
Added quotation for correct interpretation. Without it 3.10 is parsed as int and trailing zeros are cut -> 3.1
see https://github.com/MiczFlor/RPi-Jukebox-RFID/pull/1933

Update python version matrix

---

scripts/installscripts/buster-install-default-with-autohotspot.sh
scripts/installscripts/buster-install-default.sh
scripts/installscripts/tests/test_installation.sh
scripts/installscripts/tests/test_installation_altuser.sh

The installation process of requirements.txt will fail if "git+ ... #egg" dependecies are defined and setuptools and/or wheels is not installed (directly or transitiv) -> "python setup.py egg_info" failed with error code 1
This is mostly relevant for minimal 'non RaspiOS' distros like DietPi.
I smoketested on RaspiOS and DietPi on RPi 4B and the installation succeeded in both cases and e.g. RFID Reader RC522 is directly working.
But im not very familiar with python, so are there any know problems in adding theses dependencies?
And i know other distros are no officially supported, but i reckon a step in this direction wouldn't be too bad.

Add new python dependecies (setuptools, wheel)

---

installation/routines/setup_jukebox_core.sh

- pyzmq: use environment variables instead of deprecated --install-options for installation

Use env variables for pyzmq 

---

.github/workflows/pythonpackage_future3.yml
requirements.txt
src/jukebox/components/battery_monitor/BatteryMonitorBase.py
src/jukebox/jukebox/playlistgenerator.py

The post commit workflow action for python3.7 are currently failing ( actually since 01.10.2022 when _importlibs-metadata_ v5.0.0 was released ) due to an incompatiblity from _sphinx_ and _flake8_ on _importlibs-metadata_ in python 3.7 .
_sphinx_ defines since Version 4.4.0 as dependecy for _importlibs-metadata_ >= 4.4 and _flake8_ >= 3.5.0 
(https://github.com/sphinx-doc/sphinx/blob/v4.4.0/setup.py).
_flake8_ from Version 4.0.0 till 5.0.4 (latest for python 3.7) has a dependecy for _importlibs-metadata_ < 4.3.
(https://github.com/PyCQA/flake8/blob/4.0.0/setup.cfg)
_flake8_ Version 3.9.2 has no version entry for the _importlibs-metadata_ dependecy.
(https://github.com/PyCQA/flake8/blob/3.9.2/setup.cfg)
So this incompatibility in dependecies causes a version drop during installation of …

Fix Workflow Actions flake8 (future3)

---

.editorconfig

Like mentioned in https://github.com/MiczFlor/RPi-Jukebox-RFID/pull/2009#discussion_r1160975441 the indent size of js files should be 2. This also applies for yaml files.
So this should be applied by the editorconfig.

Editorconfig: Fix indent_size for js and yaml files

---

.editorconfig

Like mentioned in https://github.com/MiczFlor/RPi-Jukebox-RFID/pull/2009#discussion_r1160975441 the indent size of js files should be 2. This also applies for yaml files.
So this should be applied by the editorconfig.

future3 - Editorconfig: Fix indent_size for js and yaml files

---

components/gpio_control/test/gpio_settings_test.ini
components/gpio_control/test/test_gpio_control.py

Test was running, but with the wrong configuration file.
With the correct configuration file it was failing because the content of the file was not up to date (RotaryEncoder was using wrong function call names)
After adding the correct function calls in the config the test didn't finish because os.system was never returning non zero in `led.py`. This is because os.system should find a phoniebox system service that may not be present on the machine that tests.

Make test gpio control work again

---

conftest.py
docs/sphinx/requirements.txt
src/jukebox/components/rfid/hardware/rc522_spi/requirements.txt

The pi-rc522 fork from ChisSoc is not available anymore (https://github.com/MiczFlor/RPi-Jukebox-RFID/issues/2066). 
The fork from kevinvalk (base of ChisSoc's fork) was recently merged in the main repo and released as version 2.3.0.
To ensures compatibility with future changes pin the version to 2.3.0

fix unavailable repo for pi-rc522

---

scripts/installscripts/buster-install-default.sh
scripts/installscripts/tests/test_installation.sh

Unfortunately https://github.com/MiczFlor/RPi-Jukebox-RFID/pull/2086 lacked a thing.
The new "autohotspot" config parameters are not tested in non-interactive mode and test runs.

add autohotspot config checks

---

installation/routines/setup_jukebox_core.sh

See the pyzmq instructions: https://github.com/zeromq/pyzmq/blob/main/docs/source/howto/draft.md published at https://pyzmq.readthedocs.io/en/latest/howto/draft.html nowadays

Fix pyzmq installation from source with drafts support

---

installation/routines/setup_jukebox_core.sh

See report #2094
Arguably, actually _using_ `_jukebox_core_download_prebuilt_pyzmq` could be worth it, too. But it's not used at the moment, so this is dead code.

Remove unused _jukebox_core_download_prebuilt_pyzmq

---

installation/routines/setup_jukebox_core.sh
installation/routines/setup_jukebox_webapp.sh

Hey! as described in https://github.com/MiczFlor/RPi-Jukebox-RFID/issues/2050#issuecomment-1804785695 this PR fixes the installation of the future3/branch on bookworm. In particular it adds additional options for the `pip3` installations and it installs nodejs and npm from the official sources.
closes #2050

Fix future3 installation for bookworm

---

documentation/content/developers/docker.md

Fixes the docs for changes introduced in #2074

fix docker description for windows

---

htdocs/manageFilesFolders.php
misc/sampleconfigs/lighttpd.conf.buster-default.sample
scripts/installscripts/install-jukebox.sh

If v2 is installed on Bookworm, on calling the Webinterface it results in a "403 Forbidden".
Setting the executable right for others on the home folder fixes this. Seems that opening a subfolder (htdocs) needs this permissions since Bookworm.
This was also introduced for nginx in V3 
https://github.com/MiczFlor/RPi-Jukebox-RFID/blob/c0d5a20f5bb521d09a0b0d910fc2b83dcca79e61/installation/routines/setup_jukebox_webapp.sh#L78-L79
Additionally fixed deprecation warnings for "mod_compress"

Bookworm Web Interface 403

---

docker/docker-compose.yml
src/jukebox/components/playermpd/__init__.py
src/webapp/src/components/Library/lists/index.js

[Bugfix] Webapp allows to assign single song to card

---

documentation/developers/README.md
documentation/developers/development-environment.md
documentation/developers/pyhton.md

* Added Python Development Notes
* Reformatted `development-environment.md`

[Docs] Inform about Python venv

---

.flake8
.github/workflows/pythonpackage_future3.yml
requirements.txt
run_pytest.sh
src/jukebox/misc/loggingext.py

Add running pytest to GitHub action 

---

installation/routines/setup_autohotspot.sh

With "iw reg get | grep country" received
"country DE: DFS-ETSI
country 99: DFS-UNSET"
on a RPI4 fresh install.

[Bugfix] setup_autohotspot.sh for multiple wifi country codes, use first

---

documentation/builders/audio.md
documentation/builders/concepts.md
documentation/builders/configuration.md
documentation/builders/rpc-commands.md
documentation/builders/system.md
documentation/builders/troubleshooting.md
documentation/builders/update.md
documentation/developers/coreapps.md
documentation/developers/developer-issues.md
documentation/developers/docker.md
documentation/developers/rfid/basics.md
documentation/developers/rfid/genericusb.md
documentation/developers/rfid/mfrc522_spi.md
documentation/developers/rfid/template_reader.md
resources/default-settings/jukebox.default.yaml
src/jukebox/components/rfid/hardware/fake_reader_gui/requirements.txt
src/jukebox/components/rfid/hardware/pn532_i2c_py532/requirements.txt
src/jukebox/components/rfid/hardware/rdm6300_serial/requirements.txt

This contains all doc updates from https://github.com/MiczFlor/RPi-Jukebox-RFID/pull/2144 that are not related to the venv or python docs.
- harmonize paths
- updated doc for coreapps and references
- fix execution docs for run_jukebox.py

some documentation updates

---

documentation/builders/audio.md
documentation/builders/installation.md
documentation/developers/coreapps.md
documentation/developers/pyhton.md

* Improve formatting of audio documentation to make the steps more clear (fixes also #2014)
* Link the installation documentation to the configuration
* fix missing `source` in venv description

Minor doc improvements

---

src/cli_client/pbc.c

Just added 'package' to rpc json and provided a cli option for it.

Adapt pbc.c to current json rpc spec

---

documentation/builders/README.md
documentation/builders/cli-client.md
documentation/builders/rpc-commands.md
documentation/builders/system.md
documentation/developers/README.md
documentation/developers/cli-client.md
documentation/developers/coreapps.md
documentation/developers/libzmq.md
documentation/developers/pyhton.md
src/cli_client/pbc.c

Adding some docs how to use the CLI Client for RPC commands
Changes from #1857 are probably necessary as well

Add docs for command line client for RPC 

---

.github/workflows/test_docker_debian.yml
README.md

- [update spotify notice](https://github.com/MiczFlor/RPi-Jukebox-RFID/commit/2b5bd5e96bd5ef8cea6dc1c6456c1c679d49fba1)
- [update link for calendar 2023](https://github.com/MiczFlor/RPi-Jukebox-RFID/commit/f233a8a08a819dce46fc0ac1a29360fa09c06ae6)
- [note about maintenance mode. updated links](https://github.com/MiczFlor/RPi-Jukebox-RFID/commit/0c9e3f44cf4e7441c8763d321491da9cd6ddebcc)
- [filter paths for CI installation worlflow](https://github.com/MiczFlor/RPi-Jukebox-RFID/pull/2175/commits/c4b6f7df744b5f0a27d330af7c46e8b74f806dda)

Update Readme for next release

---

docker/jukebox.Dockerfile
documentation/developers/docker.md

I noticed a few missing docs for Pulseaudio on Mac, hence I added them for other developers.

Update Pulseaudio docs for Docker on Mac

---

requirements.txt

The official pip package isn't working anymore.
Installing from git fixes this.

fix youtube-dl package

---

docker/jukebox.Dockerfile

This makes sure the 'venv' is created only after switching to the `$USER`.
This prevents permission errors if building the container in an environment where the user is not `pi`.
Closes issue #2198

future3: Jukebox.Dockerfile - Reorder 'USER' command

---

installation/routines/customize_options.sh

deactivate kioskmode installation option on armv6 devices

---

components/rfid-reader/RC522/setup_rc522.sh
scripts/Reader.py.experimental
scripts/inc.writeGlobalConfig.sh
scripts/installscripts/tests/run_installation_tests2.sh

Make use of read_id function from pirc522 package to re-enable Mifare Ultralight C support.
Since the change of the pirc522 repo, cf. #2066, #2075, #2078, I have realized issues with Mifare Ultralight C stickers in my setup (RPi Zero 2). Moving from the previous "more manual" check of uid to the read_id function of the pirc522 package fixes this issue.
ATTENTION:
Previously, a non-standard representation of NFC card uid was returned by the Mfrc522Reader class. With this change a standard representation of the NFCs uid is return which breaks all currently stored links between cards and actions. Writing a converter appears not possible due to the way "uids" were put together previously. Like in future3 the old variant was labelled "legacy".

Bugfix: re-enable Mifare Ultralight C support

---

.githooks/post-merge
documentation/builders/gpio.md
documentation/builders/update.md
installation/install-jukebox.sh

Enforcement for https://github.com/MiczFlor/RPi-Jukebox-RFID/pull/2211#issuecomment-1923241614 to not let users rerun the installer and break their existing installation.
Rerunning the installer is currently not supported as it
* doesn't remember config used in a previous installation
* doesn't clean system files written before
* overwrites setting files in the shared folder
* (doesn't support uninstalling feature)
Also the update via pull doesn't cache changes in the installation scripts, therefore this can lead to incompatibilities.
Rebuilding the Web App on `main` and `develop` is not possible, without further user interaction, as Node is not installed by default.

prevent installer rerun and remove update path

---

.github/workflows/test_docker_debian.yml
.github/workflows/test_docker_debian_codename_sub.yml

* vizualization, options, etc.
* fix branch name
* change retention days to 1

update workflow with improvements from v3

---

components/rfid-reader/RC522/setup_rc522.sh
scripts/Reader.py
scripts/Reader.py.Multi
scripts/Reader.py.experimental
scripts/Reader.py.experimental.Multi
scripts/Reader.py.original
scripts/Reader.py.pcsc
scripts/daemon_rfid_reader.py

* fixes RC522 "place not swipe" function broken (#2248)
* fix for reader.readCard() indirection (#551)
* moved readmode_uid initialization to rc522 "__init__" function
* updated rc522 implementation for "Reader.py.experimental.multi"

Fixes for rfid reader

---

installation/includes/02_helpers.sh
installation/routines/setup_jukebox_webapp.sh

fixes #1889
Note for Release:
If ipv6 is disabled during setup, nginx fails to start.
To fix this on an existing installation please run: 
`sed -i '/listen \[::\]:80/d' /etc/nginx/sites-available/default`

Fix for nginx with disabled ipv6

---

documentation/builders/README.md
documentation/builders/components/power/batterymonitor.md
src/jukebox/components/battery_monitor/batt_mon_i2c_ads1015/__init__.py

to make it easier for users to find this howto

Extract docs for battery monitor

---

.github/workflows/test_docker_debian.yml
.github/workflows/test_docker_debian_codename_sub.yml

upload-artifact and download-artifact in v4
[Bump actions/download-artifact from 3 to 4](https://github.com/MiczFlor/RPi-Jukebox-RFID/pull/2230)
[Bump actions/upload-artifact from 3 to 4](https://github.com/MiczFlor/RPi-Jukebox-RFID/pull/2195)
[Bump geekyeggo/delete-artifact from 2 to 4](https://github.com/MiczFlor/RPi-Jukebox-RFID/pull/2193)
-> Possible solution for needed write access token on PRs if implemented  (https://github.com/GeekyEggo/delete-artifact/issues/19)

github actions update

---

components/smart-home-automation/MQTT-protocol/daemon_mqtt_client.py

https://github.com/MiczFlor/RPi-Jukebox-RFID/discussions/2263
> Seems like a new Version (2.0.0) of the plugin was released last week, that included breaking changes.
https://github.com/eclipse/paho.mqtt.python/blob/v2.0.0/docs/migrations.rst

add api version to mqtt.client for new version 2.0.0 compatibility

---

docker/armv7/jukebox.Dockerfile
docker/jukebox.Dockerfile
installation/routines/setup_jukebox_core.sh
src/jukebox/jukebox/version.py

fixes #2271
pyzmq installation fails due to the latest prerelease.
Fix: removed the `--pre` argument to use the latest release, which is known to work.

Hotfix for pyzmq installation

---

components/bluetooth-sink-switch/README.md
scripts/installscripts/install-jukebox.sh
scripts/installscripts/tests/run_installation_tests.sh
scripts/installscripts/tests/run_installation_tests2.sh
scripts/installscripts/tests/run_installation_tests3.sh

closes #2274 
- read out audio interface names with `sudo` to get the correct entries
- use the first entry as default iface name
- fallback to `PCM` if no entries are present (e.g. Pi Zero)
- Wiki has been updated for usage of `sudo amixer scontrols`

fix audio interface name in setup

---

.github/workflows/test_docker_debian_codename_sub_v3.yml

The action [GeekyEggo/delete-artifact ](https://github.com/GeekyEggo/delete-artifact) has been released in v5.
This fixes the need of a token and we can use it again for PRs.

Reactivate delete artifact 

---

.github/workflows/test_docker_debian_codename_sub.yml

The action [GeekyEggo/delete-artifact ](https://github.com/GeekyEggo/delete-artifact) has been released in v5.
This fixes the need of a token and we can use it again for PRs.

Reactivate delete artifact

---

ci/Dockerfile.debian
components/audio/PirateAudioHAT/README.md
components/audio/PirateAudioHAT/setup_pirateAudioHAT.sh
scripts/helperscripts/inc.systemHelper.sh

Up to Bullseye, the `config.txt` file is located at `/boot/`. Since Bookworm, the location changed to `/boot/firmware/`, [see here](https://www.raspberrypi.com/documentation/computers/config_txt.html).
- Added logic to retrieve correct path from future3 as helperscript
- fixed gpio service name in pirateHat setup
closes #2262

Fix path to config.txt for bookworm support

---

documentation/builders/gpio.md

The GPIO docs use `IncreaseVolume` as a name for the shutdown button. This should obviously be `Shutdown` or something similar.

Docs: Fix GPIO shutdown button naming

---

documentation/builders/update.md

Providing a page to manually update the Phoniebox update in case someone wants to get the most recent Git updates (This is not necessarily a safe path in all situations)

docs: Manually upgrade to the latest version

---

src/jukebox/components/playermpd/__init__.py

rewind() is documented to jump to the first song of the playlist. Instead, it jumped to the second song as `SONGPOS` in `MPDClient.play(SONGPOS)` is zero-indexed [1], so `mpd.play(1)` started the second song.
The change should probably be double-checked to be correct (or why it hasn't been found by now), but this is what I've observed during experimentation and doc reading.
[1] https://mpd.readthedocs.io/en/latest/protocol.html#the-queue :
> "The position is a 0-based index"
Related: #2294

Fix PlayerMPD.rewind to start with the first song (future3)

---

requirements.txt
src/jukebox/components/playermpd/__init__.py
src/jukebox/components/playermpd/coverart_cache_manager.py
src/jukebox/components/rpc_command_alias.py
src/webapp/src/components/Library/lists/albums/album-list/album-list-item.js

Previously, an ERROR was logged for each song without cover art when the Web UI was open.
This commit avoids the error, caches the no-cover-art result and saves a roundtrip to mpd for all no-cover-art songs.
Note: This will start creating an empty file for each song without cover art in order to speed up the listing. This might be surprising at first, but is in line with how the current caching mechanism works.

Fix CoverartCacheManager

---

.github/workflows/codeql-analysis_v3.yml
.github/workflows/pythonpackage_future3.yml
src/jukebox/misc/loggingext.py

- Update actions/checkout to v4
- Update actions/setup-python to v5
fixes Node.js 16 deprecation warning:
`Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v3, actions/setup-python@v4. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/ `
Switch from `CODEQL_PYTHON` to `CODEQL_EXTRACTOR_PYTHON_ANALYSIS_VERSION`.

maint: Update actions

---

docker/Dockerfile.jukebox
requirements.txt

After `pyzmq` has released the latest version, Docker was not building properly anymore. Adding cmake as a Python dependency solves this problem

fix: docker build after pyzmq update

---

documentation/builders/README.md
documentation/builders/webapp/cover-art.md
resources/default-settings/jukebox.default.yaml
src/jukebox/components/misc.py
src/jukebox/components/playermpd/coverart_cache_manager.py
src/webapp/public/locales/de/translation.json
src/webapp/public/locales/en/translation.json
src/webapp/src/App.js
src/webapp/src/commands/index.js
src/webapp/src/components/Library/lists/albums/album-list/album-list-item.js
src/webapp/src/components/Player/index.js
src/webapp/src/components/Settings/general/index.js
src/webapp/src/components/Settings/general/show-covers.js
src/webapp/src/components/Settings/index.js
src/webapp/src/context/appsettings/context.js
src/webapp/src/context/appsettings/index.js

feat: Allow to enable/disable Cover Art in Web App & load from filesystem

---

components/audio/PirateAudioHAT/setup_pirateAudioHAT.sh
components/controls/buttons_usb_encoder/setup-buttons-usb-encoder.sh
components/rfid-reader/PN532/setup_pn532.sh
components/rfid-reader/RC522/setup_rc522.sh
scripts/RegisterDevice.py.Multi

- Set default option to yes for some setups for easier handling and consistent behavior.
- Fixed possible answers for multi reader registration.

Update default handling for yes/no questions

---

.github/workflows/codeql-analysis_v3.yml

Fix warning `The setup-python-dependencies input is deprecated and no longer has any effect`.
This input is without effect, see also https://github.blog/changelog/2024-01-23-codeql-2-16-python-dependency-installation-disabled-new-queries-and-bug-fixes/

(maint) Remove setup-python-dependencies

---

components/gpio_control/GPIODevices/simple_button.py
components/gpio_control/README.md
components/gpio_control/test/test_SimpleButton.py

I had this change laying around for some time, but with the gathered reports in https://github.com/MiczFlor/RPi-Jukebox-RFID/issues/1666 it may be worth to bring it in.
---
Introduce changes to the button function calling behavior, to not trigger both function if the button is held. Though this behavior is documented, it is still counter intuitive and likely the uncommon case.
For the "SecondFunc" `hold_mode` the new behavior is:
- `SecondFunc`
- only main function is executed if button is NOT held past `hold_time`
- only secondary function is executed if button is held past `hold_time`
- `SecondFuncRepeat`
- only main function is executed if button is NOT held past `hold_time`
- only secondary function is executed if button is held past `hold_time` and repeatedly if button is futher held …

Fix button SecondFunc trigger

---

components/rfid-reader/RC522/README.md

More details, which cards work for RC522.
See discussion #2340 and PR #2372

document working cards for rc522

---

requirements-spotify.txt
scripts/installscripts/install-jukebox.sh

This should fix #2429.
Everyone experiencing this issue is invited to test this fix.

Fix Spotify authentication 

---

installation/includes/02_helpers.sh
src/jukebox/components/rfid/hardware/rdm6300_serial/setup.inc.sh

- Fixes #2444 - original problem see https://github.com/raspberrypi/bookworm-feedback/issues/114#issuecomment-1776113246
- add function to check bookworm

Use correct raspi-config command for bookworm
