docs/CONFIGURE.md
misc/rfid-reader.service
misc/startup-sound.service

since most modern linux distributions use systemd to start the system service, it makes sense to use this also to start the jukebox service.

move startup to systemd service files

---

docs/MANUAL.md
htdocs/index.php
scripts/rfid_trigger_play.sh.sample

This allows playing folders with spaces in them.

Allow spaces in folder names (web app)

---

htdocs/inc.controlPlayer.php
htdocs/inc.vlcStatus.php
htdocs/index.php

It get's the played track and play status from vlc remote via telnet and the command `status`. The play status will be shown and the player controls will be changed depend on playing or pausing of the track. The track title (folder and file) or stream url will be extracted and shown.

get play status and track title from vlc rc and show it

---

scripts/resume_play.sh

If one resumes and listens to end of the playlist there's no call of "savepos". Thatswhy next time the audio will be started by "resume" at the same position like before and not at the beginning of the playlist as one might expect.
This is fixed by adding a flag to the lastplayed.dat by "resume":
On calling of "resume" the flag will set to "Playing". "Savepos" will change it to "Stopped" when a stop/clearplaylist/shutdown event occurs. If "resume" still finds the flag "Playing" on its next call, it assumes that you have listened to end of the playlist (or you have ripped the power cord out of your Pi, but that should be punished anyway) and starts the playout at the beginning of the playlist.

Proper resume after end of playlist

---

scripts/playout_controls.sh

Volume control is now done by mpd. As a Audio-Interface setting has to be done in mpd.conf, we don't need a Audio_iFace_Name file anymore to avoid setting the same thing twice at different places.

Volume control by mpd

---

scripts/playout_controls.sh

Fix for sleep timer, Part 2

---

htdocs/inc.maxVolumeSelect.php
htdocs/inc.volumeSelect.php
htdocs/inc.volumeStepSelect.php

The actual values of the volume settings will be preselected in the forms now.

preselect actual setting values in volume setting form

---

README.md
docs/CONFIGURE-jessie.md
docs/CONFIGURE-stretch.md
docs/FIRMWARE_UPDATE.md
docs/GALLERY.md
docs/GPIO-BUTTONS.md
docs/INSTALL-jessie.md
docs/INSTALL-stretch.md
docs/MANUAL.md
htdocs/cardEdit.php
htdocs/settings.php
scripts/Reader.py
scripts/installscripts/jessie-install-default-01.sh

In many files the word jukebox appears. So that the descriptions are consistent, I have changed the wording of jukebox on Phoniebox.
folder docs/
and one to three appearance in the web app updated

Wording update jukebox becomes Phoniebox

---

htdocs/inc.navigation.php
htdocs/systemInfo.php

To get information about the phonie I'm connected to, I implement another page on the webinterface.
No special magic but some basic information, sometimes helpfully for troubleshoot.
Also on this page you get an overview of the usage of storage, maybe important if running out of free space.
I tested it only on my real raspi and on a virtual one, hope it works on other phonies as well.

Added systeminfo page

---

htdocs/inc.volumeSelect.php
htdocs/index.php

for example: limit is set by 60% all options above are now disabled.
Additional info next to the limit volume.

add volume limit info in drop-downs and a little improvment on web-ui

---

docs/INSTALL-stretch.md
htdocs/cardRegisterNew.php
htdocs/inc.formCardEdit.php
htdocs/inc.processAddYT.php
scripts/installscripts/jessie-install-default-01.sh
scripts/installscripts/stretch-install-default-01.sh

Adding YouTube audio download functionality

---

README.md
docs/CONFIGURE-jessie.md
docs/CONFIGURE-stretch.md
docs/FIRMWARE_UPDATE.md
docs/GALLERY.md
docs/GPIO-BUTTONS.md
docs/INSTALL-jessie.md
docs/INSTALL-stretch.md
docs/MANUAL.md
docs/UPGRADE.md
docs/WLAN-ACCESS-POINT.md
htdocs/cardEdit.php
htdocs/inc.navigation.php
htdocs/settings.php
htdocs/systemInfo.php
scripts/Reader.py

Solved merge conflicts and cherrypicked patches to reduce the delta between the two branches.

Merge from master

---

scripts/resume_play.sh

Fix for #110

---

htdocs/inc.loadedPlaylist.php
htdocs/inc.playerStatus.php
htdocs/index.php
scripts/playout_controls.sh
scripts/resume_play.sh

Displays loaded playlist on web app and let you choose a song from it.
Sorry @MiczFlor for messing up the index.php again. Looking forward to your UI improvements ;-)

Display loaded playlist on web app

---

htdocs/cardRegisterNew.php
htdocs/inc.formCardEdit.php

While adding the YouTube support, the "normal" card registering broke.

Fix card registering

---

htdocs/inc.header.php
scripts/playout_controls.sh

Made the seek command more flexible and condensed it to a single command in playout_controls.
Fixed a small issue if one tries to seek back to negative elapsed times.
Also removed a one second delay after pressing "play", the connection to mpd was not closed.

Improvements to the seek command

---

README.md
docs/UPGRADE.md
htdocs/inc.header.php
htdocs/trackEdit.php
scripts/installscripts/stretch-install-default.sh

* fix trackEdit.php for metadata management 
* audiofolders added and install script

fix trackEdit.php and audiofolders

---

docs/INSTALL-stretch.md

Adding how to modify php.ini to allow file upload via web app

docs php.ini config

---

htdocs/inc.viewFolderTree.php

actuall, nicer fix for relative path in web app

fixing #204 and #202

---

.gitignore
docs/MANUAL.md

Adding info from #195 to the documentation

hifiberry DAC+ soundcard infos in docs

---

htdocs/_assets/bootstrap-3/css/bootstrap.darkly.css
htdocs/func.php
htdocs/inc.controlPlayer.php

Using a darker theme for the web app

web app UI tweaks

---

htdocs/_assets/bootstrap-3/css/bootstrap.darkly.css

Adding Source Sans Pro as web app ui fonts

web app ui theme fonts

---

htdocs/_assets/css/collapsible.css
htdocs/fileUpload.php
htdocs/func.php

Making it eaiser to upload several files at a time with html5 multiple input field.
Several other adaptions, like moving the php.ini hint into a collapsible, only allow audio uploads and using proper bootstrap markup.

Task improve uploading

---

.gitignore
docs/MANUAL.md
docs/UPGRADE.md

I prefer to have a clean working directory. Since these files are individually set I explicitly added them to the gitignore. These files are not supposed to be part of the repo.

Task: update .gitignore

---

htdocs/inc.processAddNewStream.php

Reverts MiczFlor/RPi-Jukebox-RFID#238

Revert "Update inc.processAddNewStream.php"

---

htdocs/userScripts.php

Scriptfile preview to check details about parameters used or order of parameters

added scriptfile preview

---

htdocs/ajax.loadControls.php
htdocs/ajax.loadCover.php
htdocs/ajax.loadInfo.php
htdocs/ajax.loadOverallTime.php
htdocs/ajax.loadTime.php
htdocs/config.php.sample
htdocs/func.php
htdocs/image.php
htdocs/inc.controlPlayer.php
htdocs/inc.formCardEdit.php
htdocs/inc.loadedPlaylist.php
htdocs/inc.navigation.php
htdocs/inc.playerStatus.php
htdocs/inc.processAddNewStream.php
htdocs/inc.setVolume.php
htdocs/inc.viewFolderTree.php
htdocs/lang/lang-en.php
misc/rfid-reader.service
misc/startup-sound.service
scripts/playlist_recursive_by_folder.php
scripts/playout_controls.sh
scripts/rfid_trigger_play.sh
scripts/shuffle_play.sh

This is a full integration of spotify (via mopidy) and some other improvements to phoniebox.
Before you try to use: @MiczFlor has to integrate some things to his installerscript first. I have a step-by-step guide, which has to be validated first.
(Installation and Configuration of MOPIDY is necessary to use!)
Stay tuned...

Spotify integration

---

scripts/installscripts/stretch-install-default.sh
scripts/installscripts/stretch-install-spotify.sh

Adding the playlist file ending `m3u` for the default installation and `m3u8` for the spotify / mopidy installation in the one line install scripts

install script default and spotify add file ending

---

docs/GPIO-BUTTONS.md
misc/sampleconfigs/gpio-buttons.py.sample-2

updated docs and additional script in sampleconfig folder

GPIO update and additional sample script

---

htdocs/ajax.loadPlaylist.php
htdocs/func.php
htdocs/inc.formCardEdit.php
htdocs/inc.header.php
htdocs/inc.loadedPlaylist.php
htdocs/inc.processCheckCardEditRegister.php
htdocs/inc.setSleeptimer.php
htdocs/inc.setWebUI.php
htdocs/inc.viewFolderTree.php
htdocs/lang/lang-en.php
htdocs/manageFilesFolders.php
htdocs/settings.php
scripts/installscripts/stretch-install-default.sh
scripts/installscripts/stretch-install-spotify.sh
scripts/playlist_recursive_by_folder.php

I integrated automatic cover & title download. The title of spotify playlists will be stored in a title.txt in every audiofolder. This reduces the requests to the Spotify API when reloading the main page.
The automatic download is started ONCE when the main page is loaded and it checks, if the files are existing. If not, they will be requested from the API and stored locally. The main page is loading faster because of getting all informations locally then.
I integrated an option on the Settings Page, if cover will be shown or not.

Improvements for the WebUI

---

docs/SPOTIFY-INTEGRATION.md

just apt-get install necessary git tools

(docs) install git tools

---

README.md

Fix link to soundcard integration

---

scripts/playlist_recursive_by_folder.php

Fixed typo in playlist_recursive_by_folder.php which prevented files from being played.

Fixed typo in playlist_recursive_by_folder.php

---

scripts/playlist_recursive_by_folder.php

Ignoring the database file 'Thumbs.db' which is created automatically by windows.
Source code change is untested, since I do not have a testing environment I could use.
Should work, though, it's only a 1 line change.

Ignore file 'Thumbs.db'

---

docs/PHONIEBOX_ReadOnly.md

Hi @MiczFlor,
finally this is a pull request to my recently closed issue #37.
I had delivered both builds of my Phoniebox and just got my hands on one for an update, so I could update my documentation the the current system and test it on a real system before submitting it.

Added Documentation how to convert the Phoniebox in Read-Only Mode

---

misc/sampleconfigs/gpio-buttons.py.sample
scripts/playout_controls.sh

Playback-Functionality of latest recorded WAV file in $AUDIOFILES/Recordings added to playout controls.
Sample button config for recording when button X is in pressed state and for playback when button Y is pressed.

Playback-Functionality

---

htdocs/inc.langLoad.php
htdocs/inc.setLanguage.php

missed some files with the last merge...

adding language select option to settings page #423

---

htdocs/inc.setStoptimer.php

Hi,
I did a quick fix for https://github.com/MiczFlor/RPi-Jukebox-RFID/issues/479
It's my first pull request here on github, so I hope I did everything right. Is it correct to make the pr against the master branch?

(maint) fix #479

---

scripts/playout_controls.sh

First remove playerstop timer if existent, then add the new one.

 (maint) fix #479 and #484 

---

htdocs/ajax.loadOverallTime.php
htdocs/ajax.loadPlaylist.php
htdocs/ajax.loadTime.php

Using gmdate instead of date where format is displaying hour part. Fixes #566

Using gmdate instead of date

---

htdocs/func.php
htdocs/inc.header.php
htdocs/inc.viewFolderTree.php
scripts/playlist_recursive_by_folder.php
scripts/rfid_trigger_play.sh

This should fix https://github.com/MiczFlor/RPi-Jukebox-RFID/issues/570
I corrected the way parameters were passed between PHP scripts and also the handling of command line parameters. "&" is a very special char in PHP so it's necessary to use proper character handling by using urlencode and so on.

Bugfix for ampersands "&" in folder names

---

htdocs/inc.loadedPlaylist.php
htdocs/settings.php

Also fixes a javascript error when no playlist is present.
When testing the last PR, I found these two issues. Other than that it is still working fine for me.
Sorry about all the whitespace changes, that was done by my IDE.

Fix current volume is not displayed on settings page

---

htdocs/manageFilesFolders.php

- dynamic path to php.ini (the one that is currently loaded by the webserver)
- current values for file_uploads, upload_max_filesize, max_file_uploads and post_max_size

dynamic info about upload issues

---

scripts/installscripts/buster-install-default.sh

Just a little change for the pull request of the RegisterDevice.py

Needed for pull request #707

---

scripts/RegisterDevice.py

Should be called with python3!

Make it python3 ready

---

scripts/installscripts/buster-install-default.sh

Changing away from branch develop, copy the files after cloning...

Changed to Master an copy Files manual!

---

misc/sampleconfigs/phoniebox-rfid-reader.service.stretch-default.sample

Tested with a fresh install, all is working, please update to master branch!

Works with new Onelineinstaller

---

misc/sampleconfigs/gpio-buttons.py.sample

So i switched generally to variables beginning with btn_.

Variable next is internal python code

---

scripts/installscripts/buster-install-default.sh

Working Mopidy
Working Iris
Working RegisterReader
Working ReaderService
Notice, you need also the following files in the master branch:
RegisterDevice.py MiczFlor#707
phoniebox-rfid-reader.service.stretch-default.sample MiczFlor#729

Tested for fresh installations

---

scripts/installscripts/buster-install-mopidy3.sh

this got lost during work on #720 
to avoid further conflicts between fixes for mopidy-2.3.1 and conversion to python3/mopidy3, I duplicated the installer script.

feat: restore changes from #701 in separate file

---

htdocs/inc.header.php
htdocs/inc.setInputDevices.php
htdocs/lang/lang-de-DE.php
htdocs/lang/lang-en-UK.php
htdocs/lang/lang-nl-NL.php
scripts/installscripts/buster-install-default.sh

added the configuration for the rotary knob:
https://github.com/MiczFlor/RPi-Jukebox-RFID/wiki/Audio-RotaryKnobVolume
But I have the problem, that in the Webinterface I didn't get the label working. Do I have to reinitialize the language-files?

Configure the Rotary Knob

---

.github/workflows/pythonpackage.yml
scripts/MFRC522.py
scripts/Reader.py
scripts/Reader.py.experimental
scripts/Reader.py.kkmoonRFIDreader
scripts/RegisterDevice.py
scripts/activate_amplifier.py
scripts/daemon_mqtt_client.py
scripts/daemon_rfid_reader.py
scripts/pirc522/rfid.py
scripts/pirc522/util.py
scripts/python-phoniebox/ConfigParserExtended.py
scripts/python-phoniebox/Phoniebox.py
scripts/python-phoniebox/PhonieboxConfigChanger.py
scripts/python-phoniebox/PhonieboxDaemon.py
scripts/python-phoniebox/RawConfigParserExtended.py
scripts/python-phoniebox/Reader.py
scripts/rotary-encoder.py
scripts/rotary_encoder_base.py

I migrated remaining code to Python3 and fixed some warnings from linter flake8.

Migrate code to python 3

---

ci/Dockerfile.amd64
ci/Dockerfile.armv7
ci/README.md

* renamed the armv7 Dockerfile as well for clarification.
* adapted README accordingly

feat: dockerfile for amd64 machines

---

.github/workflows/pythonpackage.yml
ci/Dockerfile.amd64
ci/Dockerfile.armv7
ci/README.md
misc/sampleconfigs/gpio-buttons-with-twobuttonshortcut.py.sample
misc/sampleconfigs/gpio-buttons.py.rotaryencoder.sample
misc/sampleconfigs/gpio-buttons.py.sample
scripts/Reader.py.experimental
scripts/Reader.py.kkmoonRFIDreader
scripts/python-phoniebox/Phoniebox.py
scripts/python-phoniebox/PhonieboxConfigChanger.py
scripts/python-phoniebox/PhonieboxDaemon.py
scripts/python-phoniebox/Reader.py
scripts/python-phoniebox/helpers_unused_atm/helpers.py

* fixed flake8 formatting warnings
* Github Actions only for Python 3.7

fixed warnings and simplified Github Actions

---

.editorconfig

https://editorconfig.org/ says:
"EditorConfig helps maintain consistent coding styles for multiple 
developers working on the same project across various editors and IDEs. 
The EditorConfig project consists of a file format for defining coding 
styles and a collection of text editor plugins that enable editors to 
read the file format and adhere to defined styles. EditorConfig files 
are easily readable and they work nicely with version control systems."

feat: introduce editorconfig to the project

---

scripts/installscripts/buster-install-default.sh
scripts/installscripts/buster-install-mopidy3.sh
scripts/installscripts/stretch-install-default-HotspotAddOn.sh
scripts/installscripts/stretch-install-default.sh
scripts/installscripts/stretch-install-spotify.sh

this contains a lot of (non-functional) whitespace changes, so it might be best to review the functional changes with whitespaces ignored in the diff view

fix: fixed shellcheck complaints and indentation on install scripts

---

.github/ISSUE_TEMPLATE/bug_template.md
.github/ISSUE_TEMPLATE/feature_template.md
.gitignore

This is just a suggestion on how these could look - your input is very much welcome and even requested

chore: issue templates for bugs and features

---

ci/Dockerfile.buster.amd64
ci/Dockerfile.buster.armv7
ci/Dockerfile.stretch.amd64
ci/Dockerfile.stretch.armv7
ci/README.md
scripts/installscripts/buster-install-default.sh
scripts/installscripts/buster-install-mopidy3.sh
scripts/installscripts/stretch-install-default.sh
scripts/installscripts/stretch-install-spotify.sh

renamed buster Dockerfiles to highlight the difference

feat: add dockerfiles for stretch as well

---

.github/workflows/pythonpackage.yml
misc/sampleconfigs/phoniebox-rfid-reader.service.stretch-default.sample

Applying changes proposed in #747

Hotfix: Make RFID reader service working again

---

.github/workflows/pythonpackage.yml
scripts/installscripts/stretch-install-default.sh
scripts/installscripts/stretch-install-spotify.sh

**UNTESTED YET**, because I don't have a stretch environment
Issues #747 and #749 are probably related

use python3 also for stretch

---

.github/ISSUE_TEMPLATE/bug_template.md
.github/ISSUE_TEMPLATE/feature_template.md

this replaces the emoticon :bug: and :bulb: with utf-8 character codes.

fix: icons in issue templates

---

.github/workflows/pythonpackage.yml
scripts/installscripts/buster-install-default.sh
scripts/installscripts/buster-install-mopidy3.sh
scripts/installscripts/stretch-install-default.sh
scripts/installscripts/stretch-install-spotify.sh

For improved debugging `git statusˋ prints, which branch was cloned.

Add check, which branch was cloned

---

scripts/installscripts/buster-install-default.sh

Use fix from #771 also on master.
Supposed to fix issue #783

Use mopidy 2.2 also on master

---

scripts/installscripts/buster-install-mopidy3.sh

Implement #803 to support #796

Upgrade to Mopidy 3

---

scripts/installscripts/buster-install-default.sh

fixed minor bug in installation script

check git status correctly

---

scripts/installscripts/buster-install-default.sh
scripts/installscripts/buster-install-mopidy3.sh

Found an bad line during installation in #803 
Replaced it with checking first before deleting

better handling on removing global.conf

---

docs/SPOTIFY-INTEGRATION.md
scripts/installscripts/buster-install-default.sh

so changes from PR #804 are reflected.

Update spotify description

---

misc/sampleconfigs/phoniebox-mqtt-client.service.stretch-default.sample

File name on ˋmasterˋ is still with underscores

Fixed file name

---

misc/sampleconfigs/phoniebox-activate-amplifier.service.stretch-default.sample
misc/sampleconfigs/phoniebox-gpio-buttons.service.stretch-default.sample
misc/sampleconfigs/phoniebox-rfid-reader.service.stretch-default.sample
misc/sampleconfigs/phoniebox-rotary-encoder.service.stretch-default.sample

Shebang inside py files is sufficient. See #796

Fix servicectl config files

---

scripts/installscripts/buster-install-default.sh

Remove also fpm service

---

scripts/installscripts/buster-install-default.sh

See #796.
Stretch should stay as it is.

Remove python 2 package installation from buster

---

ci/Dockerfile.buster.amd64
ci/Dockerfile.buster.armv7
ci/Dockerfile.stretch.amd64
ci/Dockerfile.stretch.armv7

Doing it this way is less confusing when you are working in a docker container with these images yourself and use the apt commands.
reverts #853 - sorry for being late with my review.

use non-interactive debian frontend in dockerfiles

---

components/smart-home-automation/MQTT-protocol/README.md

Add info about pkg installation

---

scripts/playout_controls.sh

as mentioned in https://github.com/MiczFlor/RPi-Jukebox-RFID/issues/860

delay shutdown if apt update/upgrade is running

---

scripts/installscripts/buster-install-default.sh

Changes have been tested with test_installation.sh script (see PR  #903) on a fresh Raspian Buster image on QEMU. Installation logs have also been compared and no unexpected difference was found.

Install script improvements2

---

scripts/installscripts/buster-install-default.sh
scripts/installscripts/tests/test_installation.sh

More cleanup of the install script. Next PR will add features. ;)
Commit has been tested successfully with test_installation.sh script and logs were compared with HEAD on develop branch. No unintended differences were found.

Install script improvements3

---

htdocs/inc.loadControls.php

add changes proposed in #889 to fix repeat function

---

scripts/installscripts/buster-install-default.sh
scripts/installscripts/tests/test_installation.sh

Non interactive install

---

scripts/installscripts/buster-install-default.sh

fixing log path

---

scripts/installscripts/tests/test_installation.sh

oversight in https://github.com/MiczFlor/RPi-Jukebox-RFID/commit/b1551b02db9f1882f3bf9cf673284d0ea98ab681
@fredg02, could you check this?

service was changed to phoniebox-startup-script 

---

scripts/installscripts/tests/run_installation_tests.sh

Use correct branch for install test - was missed in #937

---

ci/Dockerfile.buster.test_install.amd64
scripts/installscripts/tests/test_installation.sh

Remaining issues of checks on docker fixed.

Finally fix docker test

---

components/displays/HD44780-i2c/i2c_lcd_driver.py
components/gpio_control/GPIODevices/VolumeControl.py
components/gpio_control/GPIODevices/led.py
components/gpio_control/GPIODevices/rotary_encoder.py
components/gpio_control/GPIODevices/shutdown_button.py
components/gpio_control/GPIODevices/simple_button.py
components/gpio_control/GPIODevices/two_button_control.py
components/gpio_control/function_calls.py
components/gpio_control/gpio_control.py
components/gpio_control/test/test_TwoButtonControl.py
components/gpio_control/test/test_gpio_control.py
components/gpio_control/test/test_shutdown_button.py
components/smart-home-automation/MQTT-protocol/daemon-mqtt-client.py
misc/sampleconfigs/gpio-buttons-with-twobuttonshortcut.py.sample
misc/sampleconfigs/gpio-buttons.py.rotaryencoder.sample
misc/sampleconfigs/gpio-buttons.py.sample
scripts/Reader.py.experimental
scripts/Reader.py.kkmoonRFIDreader
scripts/Reader.py.original
scripts/activate_amplifier.py

fixed flake8 warnings, no functional change

fix formatting

---

htdocs/func.php
htdocs/inc.viewFolderTree.php

improves #949 
Integreates multiple Mopidy API requests of the same kind in a handy function.

Function based mopidy api calls

---

components/audio/PirateAudioHAT/README.md
components/audio/PirateAudioHAT/setup_pirateAudioHAT.sh

* Make script more robust so it can be executed multiple times without
breaking something.
* Improve README.md

Add steps to setup display and buttons on Pirate Audio HAT

---

components/rfid-reader/PN532/README.md
components/rfid-reader/PN532/setup_pn532.sh

* Remove libnfc dependency
* Workaround for changes in #962

Improve setup_pn532.sh script

---

scripts/playout_controls.sh

As requested from @MiczFlor I tried to implement the check IP into togglewifi to fix #919 .
The problem here is, I cannot test this setup since I don't have a spare RFID reader.

Added check for ip within togglewifi function

---

components/rfid-reader/PN532/README.md
components/rfid-reader/RC522/README.md
components/rfid-reader/RC522/setup_rc522.sh

added a script to install the RC522 reader.
I don't have the reader, so I couldn't test it, but the script is fairly straightforward from the Readme.
@fredg02, maybe you can have a look?

add a script to install RC522 reader

---

htdocs/inc.header.php
htdocs/inc.setIdleShutdown.php
htdocs/inc.setVolume.php
htdocs/inc.setVolumeStep.php

Add percentage sign an move settings-reading to inc.header.php

---

htdocs/cardRegisterNew.php

Fix bug in csv import

---

components/displays/HD44780-i2c/i2c_lcd.py
components/gpio_control/gpio_control.py
scripts/installscripts/buster-install-default.sh

* fixed indentation
* fixed formatting

fixed formatting & indentation

---

htdocs/inc.viewFolderTree.php

Fix warning brought up in #982

Fix warning in usort

---

components/gpio_control/example_configs/gpio_settings.ini
components/gpio_control/example_configs/gpio_settings_rotary_and_led.ini
components/gpio_control/example_configs/gpio_settings_test.ini
components/gpio_control/test/gpio_settings_test.ini

See also https://github.com/MiczFlor/RPi-Jukebox-RFID/issues/973#issuecomment-639106678
@veloxidSchweiz, could you review?

Change used type to existing

---

components/audio/PirateAudioHAT/requirements.txt
components/audio/PirateAudioHAT/setup_pirateAudioHAT.sh
components/gpio_control/install.sh
components/gpio_control/requirements.txt
components/rfid-reader/PN532/setup_pn532.sh
components/rfid-reader/RC522/requirements.txt
components/rfid-reader/RC522/setup_rc522.sh
requirements-gmusic.txt
requirements-spotify.txt
requirements.txt
scripts/installscripts/buster-install-default-with-autohotspot.sh
scripts/installscripts/buster-install-default.sh

* Force installation of python packages, even when older versions are already installed
* Harmonized python package installation
E.g. #1000 was an issue, where an old python package probably caused issues, because it wasn't upgraded.

Always upgrade Python package

---

htdocs/api/playlist/appendFileToPlaylist.php
htdocs/api/playlist/playsinglefile.php
htdocs/func.php
htdocs/js/jukebox.js

Fix "Play single file" to play filenames containing single quotes and appendFileToPlaylist

---

components/smart-home-automation/MQTT-protocol/README.md

fixed filename and changed path to be absolute (and therefore always correct)

fix filename

---

scripts/installscripts/tests/run_installation_tests.sh
scripts/installscripts/tests/run_installation_tests2.sh
scripts/installscripts/tests/test_installation.sh

Changes from #1064 considered.

Fix installscript test

---

components/gpio_control/gpio_control.py

fixed an issue where gpio controls didn't work properly

---

components/gpio_control/GPIODevices/simple_button.py

fixed an issue where arguments for playout_commands have the wrong value

---

components/gpio_control/GPIODevices/simple_button.py
components/gpio_control/test/test_SimpleButton.py

fixed unit tests

---

.github/workflows/dockerimage.yml
ci/Dockerfile.buster.test_install.amd64
misc/sampleconfigs/mopidy-etc.sample
misc/sampleconfigs/mopidy.sample
scripts/installscripts/buster-install-default.sh
scripts/installscripts/tests/run_installation_tests3.sh
scripts/installscripts/tests/test_installation.sh

Fixes #1104 
including unit tests for spotify installation

Fix custom mopidy media dir

---

scripts/resume_play.sh

Fix resume

---

components/displays/HD44780-i2c/i2c_lcd.py

Fix for #1133 (Update i2c_lcd.py to fix track number)

---

components/rfid-reader/RC522/setup_rc522.sh

Make sure, SPI works

---

components/displays/HD44780-i2c/i2c_lcd.py

Implement #1164
@Conendrum, could you check, if that’s the way it was intended?

Improve reading artist

---

components/gpio_control/example_configs/gpio_settings.ini

Closing  #1049
@veloxidSchweiz, what do you think?
updated also https://github.com/MiczFlor/RPi-Jukebox-RFID/wiki/Stop-on-removal-with-USB-RFID-Reader

Added stop on removal functionality example

---

components/gpio_control/GPIODevices/shutdown_button.py
components/gpio_control/example_configs/gpio_settings_test.ini
components/gpio_control/gpio_control.py
components/gpio_control/test/gpio_settings_test.ini
components/gpio_control/test/test_shutdown_button.py

activation of shutdown button class in gpio_control

---

components/gpio_control/GPIODevices/VolumeControl.py
components/gpio_control/function_calls.py
components/gpio_control/gpio_control.py

I am intending to do some enhancements on the gpio_control, here especially the function_calls in the future. (see post in #774)
It would be best to do this in a derived class.
Therefore I tried to convert the gpio_control and function_calls into classes, without influence to the actual functionality.
I am unsure if the logging now is still doing how it was originally intended, and just could do limited testing.
At least on my box everything is working as before.
This can can most likely be rated as a general improvement to the program structure.
(sorry I messed up my develop branch, I just got aware that I deleted accidentally the previous pull request (#1299) due to that)

refactoring gpio-control to class

---

scripts/Reader.py.experimental

Fix missing import

---

components/controls/buttons_usb_encoder/buttons_usb_encoder.py
components/controls/buttons_usb_encoder/map_buttons_usb_encoder.py
components/displays/HD44780-i2c/i2c_lcd.py

This update form @arne123 fixes #1320 .
There was still a Bug in the Import of the class function. and here is my commit.
@s-martin  I tested this on my setup and it looks like it works now. Please can somebody verify since I am not at home in Python.

Bugfix #1320  of arne123/RPi-Jukebox-RFID/tree/gpio-control_to_class

---

components/bluetooth-sink-switch/README.md
components/bluetooth-sink-switch/bt-sink-switch.py
components/bluetooth-sink-switch/install-bt-sink-switch.sh

Use gpio_settings.ini for Bluetooth Toggle LED configuration

---

components/bluetooth-sink-switch/bt-sink-switch.py

Fixes issue #1347: Small adjustment to regexp.

Fix for Issue #1347

---

Phoniebox/PhonieboxDaemon.py
Phoniebox/rfid_reader/PhonieboxRfidReader.py
Phoniebox/rpc/PhonieboxRpcClient.py
Phoniebox/rpc/PhonieboxRpcServer.py
README.md
docs/phoniebox.conf.example

added the possibility to use inproc communication for the RPC Server and Client when used in a single process and zmq context

allowed single process/zmq_context communication (inproc)

---

.github/ISSUE_TEMPLATE/future1.md
.github/ISSUE_TEMPLATE/future3.md
.github/workflows/dockerimage.yml
.github/workflows/pythonpackage_future3.yml

Workflows for Future3/**
Relates to  #1410

Workflows for Future3

---

.github/workflows/pythonpackage_future3.yml

Fix in future3 github workflow

Fix in future3 github workflow

---

settings/jukebox.yaml
src/jukebox/jukebox/rpc/server.py

After the recent change, the websocket support was gone. This commit brings it back it.

[bugfix] add websocket channel again

---

README.md
resources/default-settings/jukebox.default.yaml
src/jukebox/components/alsaif/__init__.py
src/jukebox/components/hostif/linux/__init__.py
src/jukebox/components/jingle/__init__.py
src/jukebox/components/playermpd/__init__.py
src/jukebox/components/rfid/fake_reader_gui/fake_reader_gui.py
src/jukebox/components/rfid/reader/__init__.py
src/jukebox/components/timers/__init__.py
src/jukebox/components/volume/__init__.py
src/jukebox/jukebox/daemon.py
src/jukebox/jukebox/multitimer.py
src/jukebox/jukebox/plugs.py

This has become quite a feature update and improvement.
See commit messages for more details.

Error-safe loading of plugins

---

README.md
resources/default-settings/cards.example.yaml
resources/default-settings/jukebox.default.yaml
src/jukebox/components/hostif/linux/__init__.py
src/jukebox/components/playermpd/__init__.py
src/jukebox/components/rfid/README.md
src/jukebox/components/rfid/cardactions.py
src/jukebox/components/rfid/cardutils.py
src/jukebox/components/rfid/configure/__init__.py
src/jukebox/components/rfid/fake_reader_gui/fake_reader_gui.py
src/jukebox/components/rfid/rdm6300_serial/description.py
src/jukebox/components/rfid/reader/__init__.py
src/jukebox/jukebox/cfghandler.py
src/jukebox/jukebox/plugs.py
src/jukebox/jukebox/utils.py
src/jukebox/misc/__init__.py

See [components/rfid/README.md](https://github.com/MiczFlor/RPi-Jukebox-RFID/tree/d268e833f9440021202bd19e13fa043009a849ce/src/jukebox/components/rfid#readme) for details.

Card action short cuts, second swipe, card removal action

---

README.md
requirements.txt
resources/default-settings/jukebox.default.yaml
resources/default-settings/logger.default.yaml
src/jukebox/README.md
src/jukebox/components/alsaif/__init__.py
src/jukebox/components/hostif/linux/__init__.py
src/jukebox/components/misc.py
src/jukebox/components/playermpd/__init__.py
src/jukebox/components/publishing/__init__.py
src/jukebox/components/rfid/cards/__init__.py
src/jukebox/components/rfid/cardutils.py
src/jukebox/components/rfid/fake_reader_gui/fake_reader_gui.py
src/jukebox/components/rfid/reader/__init__.py
src/jukebox/components/timers/__init__.py
src/jukebox/jukebox/cfghandler.py
src/jukebox/jukebox/daemon.py
src/jukebox/jukebox/multitimer.py
src/jukebox/jukebox/plugs.py
src/jukebox/jukebox/publishing/__init__.py
src/jukebox/jukebox/publishing/server.py
src/jukebox/jukebox/publishing/subscriber.py
src/jukebox/jukebox/pubsub/__init__.py
src/jukebox/jukebox/pubsub/server.py
src/jukebox/jukebox/utils.py
src/jukebox/misc/loggingext.py
src/jukebox/run_jukebox.py
src/jukebox/run_publicity_sniffer.py
src/jukebox/run_rpc_tool.py

Publishing: subscriber detection, last value cache, multi-part messages
--> as discussed this will break the interface to the WebUI. @pabera knows about it :-)
Card handling functions
Error log publishing 
Debug/Analysis tools (Check out the new Readme: src/jukebox/README.md)

Cumulative major update (especially extended publishing concept)

---

.gitignore
README.md
requirements.txt
src/jukebox/components/hostif/linux/__init__.py
src/jukebox/components/misc.py
src/jukebox/components/playermpd/__init__.py
src/jukebox/components/publishing/__init__.py
src/jukebox/components/rfid/cards/__init__.py
src/jukebox/components/rfid/reader/__init__.py
src/jukebox/components/timers/__init__.py
src/jukebox/jukebox/daemon.py
src/jukebox/jukebox/multitimer.py
src/jukebox/jukebox/plugs.py
src/jukebox/misc/__init__.py
src/jukebox/misc/loggingext.py
src/jukebox/run_jukebox.py
src/jukebox/run_register_rfid_reader.py
src/jukebox/run_rpc_tool.py

... and a few other goodies :-)

Add getter for log outputs via RPC

---

resources/default-settings/jukebox.default.yaml
src/jukebox/components/music_cover_art/__init__.py
src/webapp/src/components/Player/cover.js
src/webapp/src/config.js
src/webapp/src/context/player/context.js
src/webapp/src/context/player/index.js
src/webapp/src/utils/requests.js
src/webapp/src/utils/utils.js

This is a simple jukebox plugin to read the cover art of a given music file. It returns it as base64 to avoid writing to HDD.
additionally, the cover is also being shown in the webapp interface

Introducing simple cover art

---

installation/routines/setup_jukebox_webapp.sh
src/webapp/run_rebuild.sh

Needed for Bullseye on RP 3A (and probably others)
- the run_rebuild.sh is testet
- the installation script adaption not yet

Check free memory before building Web UI

---

docs/sphinx/_templates/footer.html
docs/sphinx/conf.py
installation/routines/customize_options.sh
installation/routines/setup_jukebox_webapp.sh
resources/default-settings/nginx.default

Make docs locally avaiable on http://ip.of.your.box/docs
This is integrated as install option

Options to serve docs on locally RPi Nginx server

---

src/jukebox/components/playermpd/__init__.py

Prevent socket timeout in MPD player interface

---

installation/routines/customize_options.sh

Typo - fixes #1693

---

docs/sphinx/userguide/troubleshooting.rst
resources/default-settings/nginx.default
resources/html/404.html
resources/html/runsphinx.html

Make log files accessible via http://ip.of.your.box/logs

Add access to Jukebox log files via web server

---

docs/sphinx/api/api.rst
docs/sphinx/api/controls.rst
docs/sphinx/index.rst
docs/sphinx/userguide/bluetooth_audio_buttons.rst
resources/default-settings/jukebox.default.yaml
src/jukebox/components/controls/bluetooth_audio_buttons/README.rst
src/jukebox/components/controls/bluetooth_audio_buttons/__init__.py
src/jukebox/components/controls/common/evdev_listener.py
src/jukebox/components/controls/evdev_listener.py
src/jukebox/components/volume/__init__.py

When a bluetooth sound device (headphone, speakers) connects
attempt to automatically listen to it's buttons (play, next, ...)

Add new feature: Bluetooth sound device button listener

---

src/jukebox/components/gpio/gpio_rpi/README.rst

Changed the commands to be correct

Rotary alias fix

---

resources/default-settings/gpio.example.yaml

It would be good to document what timebase does, i could not find anything in the docu (maybe i looked at the wrong spot

Update usage template for rotary encoder

---

installation/routines/setup_mpd.sh

Also comments on the error during installation observed in #1713

Improve MPD install routine

---

requirements.txt
src/jukebox/jukebox/rpc/server.py

Python 3.7 can use standard time module for this

(packaging) Remove nanotime dependency

---

docs/sphinx/install.rst

Changed default install script to point to future3/main as described

Correct script to use future3/main

---

components/smart-home-automation/MQTT-protocol/README.md
components/smart-home-automation/MQTT-protocol/daemon_mqtt_client.py
components/smart-home-automation/MQTT-protocol/requirements.txt

added command `shutdownvolumereduction` and attribute `remaining_shutdownvolumereduction`
Note: this is branched off of the to-be-merged #1496. Hope both can be merged in the upcoming 2.4 release.

add "shutdownvolumereduction"

---

scripts/playout_controls.sh

adjust playerpauseforce to only pauses when currently playing
see bug #1520

adjust playerpauseforce

---

scripts/idle-watchdog.sh

https://github.com/MiczFlor/RPi-Jukebox-RFID/issues/1497

quickfix idle-watchdog with amixer

---

components/rfid-reader/RC522/requirements.txt
requirements.txt

Use `git+https` instead of `git+git`

Fix git protocol for pip

---

htdocs/lang/lang-fr-FR.php

Add file lang-fr-FR.php to have French interface.

Add french language to our favorite jukebox

---

src/jukebox/components/rfid/hardware/rc522_spi/README.rst

https://pinout.xyz for source.

(docs)fixed typo in pinout doc for rc522_spi

---

htdocs/_assets/bootstrap-3/js/collapse.js

Fixes https://github.com/MiczFlor/RPi-Jukebox-RFID/security/code-scanning/1

Fix code scanning alert

---

htdocs/trackEdit.php

Signed-off-by: Feras Al-Kassar
The vulnerability explanation https://github.com/MiczFlor/RPi-Jukebox-RFID/issues/1859

Fix Command Injection and XSS vulnerabilities in trackEdit.php

---

docs/sphinx/userguide/configuration.rst

Correct paths in configuration.rst

---

docs/sphinx/primer.rst

typo and broken link to phoniebox.de, site seems down right now anyways.

typos in docs

---

.flake8

Fix count in flake8 config

---

.github/workflows/php.yml
composer.json
composer.lock

This should fix the serializable issue in the test: https://github.com/mpyw/phpunit-patch-serializable-comparison
see also: https://github.com/sebastianbergmann/phpunit/issues/4371

add patch for serializable

---

scripts/RegisterDevice.py

Improvement from https://github.com/MiczFlor/RPi-Jukebox-RFID/issues/1618#issuecomment-1464894321

Close devices

---

.github/workflows/dockerimage.yml
ci/Dockerfile.bullseye.test_install.amd64
scripts/installscripts/tests/test_installation.sh

Test installation scripts on bullseye Docker

Add bullseye Dockerfile

---

docs/sphinx/featurelist.rst
docs/sphinx/install.rst
docs/sphinx/issues.rst
docs/sphinx/migration.rst
docs/sphinx/primer.rst

ignore the massacre while i tried to figure out code-blocks.

a few more typos and wordings

---

components/rfid-reader/RC522/requirements.txt

Fix rc-522 dependency 

---

.github/workflows/pythonpackage_future3.yml
docker/armv7/jukebox.Dockerfile
docker/jukebox.Dockerfile
documentation/content/developers/development-environment.md
installation/includes/00_constants.sh
installation/routines/setup_jukebox_core.sh
installation/routines/setup_jukebox_webapp.sh
installation/routines/setup_mpd.sh
requirements.txt
resources/default-services/jukebox-daemon.service
src/jukebox/components/rfid/configure/__init__.py
src/jukebox/jukebox/multitimer.py

- fix installed packages in venv
- move venv in projekt root
- fix node setup
- update comments / messages
- #2112 fix 'not tagged as plugin callable'

Future3 fix venv usage

---

documentation/builders/README.md
documentation/builders/audio.md
documentation/builders/card-database.md
documentation/builders/configuration.md
documentation/builders/gpio.md
documentation/builders/installation.md
documentation/builders/troubleshooting.md
documentation/developers/coreapps.md
documentation/developers/developer-issues.md
documentation/developers/development-environment.md
documentation/developers/docker.md
documentation/developers/known-issues.md
documentation/developers/status.md

* Convert GPIO rst to markdown
* Move gpio.md to ./documentation
* Add WSL section
* fix markdown warnings

Improve Docs: Fix GPIO and add WSL

---

README.md

This is the change in the readme file. Requires the other Calendar 2024 request: adding the image to the repo.

Update README.md to include calendar 2024

---

.github/workflows/test_docker_debian.yml
.github/workflows/test_docker_debian_codename_sub.yml

Needed updates for new action versions. see  https://github.com/MiczFlor/RPi-Jukebox-RFID/pull/2193 and https://github.com/MiczFlor/RPi-Jukebox-RFID/pull/2195

Installation workflow dependabot updates

---

.github/workflows/test_docker_debian_v3.yml

same changes as in v2 (https://github.com/MiczFlor/RPi-Jukebox-RFID/pull/2197)

add workflow files to paths to trigger run

---

README.md

change v3 refs from develop to main

update v3 refs

---

documentation/builders/audio.md

Please ignore.
I tried to suggest 2 changes to make things clearer in 
https://github.com/MiczFlor/RPi-Jukebox-RFID/blob/future3/main/documentation/builders/installation.md#install-phoniebox-software 
and 
https://github.com/MiczFlor/RPi-Jukebox-RFID/blob/future3/main/documentation/builders/audio.md
not 787 changes !

Improve Bluetooth docs

---

resources/system/99-rpi-jukebox-rfid-welcome
src/jukebox/components/rfid/hardware/generic_usb/generic_usb.py

* fix motd code snippet
* fix message on error for generic usb reader registration

Minor fixes

---

.github/workflows/bundle_webapp_and_release_v3.yml
.github/workflows/test_docker_debian_codename_sub_v3.yml
.github/workflows/test_docker_debian_v3.yml

upload-artifact and download-artifact in v4
See https://github.com/MiczFlor/RPi-Jukebox-RFID/pull/2240

github actions update

---

src/webapp/src/components/Library/lists/index.js

fix: search filter in library

---

src/jukebox/jukebox/playlistgenerator.py
src/webapp/public/locales/de/translation.json
src/webapp/public/locales/en/translation.json
src/webapp/src/components/Cards/controls/actions/play-music/selected-folder.js
src/webapp/src/components/Library/lists/folders/folder-list-item.js
src/webapp/src/components/Library/lists/folders/folder-list.js
src/webapp/src/components/Library/lists/folders/index.js
src/webapp/src/config.js

This also allows to go back when folder is empty
Fixes #2224

fix: Stop Back Action at audiofolder root level

---

.markdownlint-cli2.yaml
documentation/builders/installation.md
documentation/developers/webapp.md

* allow html tags summary, details (MD033)
* allow recurring headings, if siblings (MD024)

Customize markdownlint

---

.github/workflows/codeql-analysis_v3.yml

- Updating to v3. Version 2 goes EOL soon.
- Add apt-get update to avoid errors like https://github.com/MiczFlor/RPi-Jukebox-RFID/actions/runs/8489937835/job/23260526231

Update CodeQL to v3

---

documentation/developers/README.md

(maint) fix links

---

documentation/developers/rfid/mfrc522_spi.md

More details, which cards work for RC522.
See discussion #2340

add details about cards for RC522

---

ci/Dockerfile.debian

https://docs.docker.com/reference/build-checks/from-as-casing/

Fix FROM as casing warning

---

docker/Dockerfile.jukebox

Fixing the same as here
* https://github.com/MiczFlor/RPi-Jukebox-RFID/pull/2449

Docker semantic fix
